import type PocketBase from "pocketbase";
import { pb } from "@/lib/pocketbase";
import { BISNIS_COLLECTIONS } from "./types";

async function resolveDocPb(): Promise<PocketBase> {
  if (typeof window !== "undefined") return pb;
  const { getInventoryAdminPb } = await import("@/lib/inventory/pb-server");
  return getInventoryAdminPb();
}

export type NumberingConfig = {
  collection: string;
  field: string;
  prefix: string;
};

/** Konfigurasi nomor urut per jenis dokumen (masing-masing sequence terpisah). */
export const BIZ_DOC_NUMBER_CONFIG = {
  po: {
    collection: BISNIS_COLLECTIONS.purchaseOrders,
    field: "po_no",
    prefix: "PO",
  },
  bill: {
    collection: BISNIS_COLLECTIONS.purchaseBills,
    field: "bill_no",
    prefix: "BILL",
  },
  so: {
    collection: BISNIS_COLLECTIONS.salesOrders,
    field: "order_no",
    prefix: "SO",
  },
  inv: {
    collection: BISNIS_COLLECTIONS.invoices,
    field: "invoice_no",
    prefix: "INV",
  },
  exp: {
    collection: BISNIS_COLLECTIONS.expenses,
    field: "expense_no",
    prefix: "EXP",
  },
  ret: {
    collection: BISNIS_COLLECTIONS.returs,
    field: "retur_no",
    prefix: "RET",
  },
  cn: {
    collection: BISNIS_COLLECTIONS.creditNotes,
    field: "cn_no",
    prefix: "CN",
  },
  imp: {
    collection: BISNIS_COLLECTIONS.salesImportBatches,
    field: "batch_no",
    prefix: "IMP",
  },
  payImp: {
    collection: BISNIS_COLLECTIONS.paymentImportBatches,
    field: "batch_no",
    prefix: "PEL",
  },
} as const satisfies Record<string, NumberingConfig>;

export type BizDocNumberKind = keyof typeof BIZ_DOC_NUMBER_CONFIG;

/** Urutan 00001–99999 per bulan, lalu reset ke 00001. */
export const DOC_SEQ_MAX = 99999;
const DOC_SEQ_PAD = 5;

export type DocNumberOpts = { periodDate?: string | Date };

function escapeFilter(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Kunci periode MMYYYY, contoh Juni 2026 → 062026. */
export function docPeriodKey(date: string | Date = new Date()): string {
  const d = typeof date === "string" ? new Date(date.includes("T") ? date : `${date}T12:00:00`) : date;
  if (Number.isNaN(d.getTime())) {
    const now = new Date();
    return `${String(now.getMonth() + 1).padStart(2, "0")}${now.getFullYear()}`;
  }
  return `${String(d.getMonth() + 1).padStart(2, "0")}${d.getFullYear()}`;
}

/** Format standar: PREFIX-MMYYYY-00001 */
export function formatDocNo(prefix: string, seq: number, periodKey: string): string {
  const clamped = ((seq - 1) % DOC_SEQ_MAX) + 1;
  return `${prefix}-${periodKey}-${String(clamped).padStart(DOC_SEQ_PAD, "0")}`;
}

export function docNoPattern(prefix: string) {
  return {
    monthly: new RegExp(`^${prefix}-(\\d{6})-(\\d{5})$`),
    /** Legacy: SO-0001 */
    global: new RegExp(`^${prefix}-(\\d{4})$`),
    /** Legacy: SO-20260531-0001 */
    dated: new RegExp(`^${prefix}-\\d{8}-(\\d+)$`),
  };
}

export function parseDocNoParts(
  value: string,
  prefix: string,
): { periodKey: string; seq: number } | null {
  const trimmed = value.trim();
  const { monthly, global, dated } = docNoPattern(prefix);

  const m = trimmed.match(monthly);
  if (m) {
    const n = Number(m[2]);
    if (n >= 1 && n <= DOC_SEQ_MAX) return { periodKey: m[1], seq: n };
  }

  const g = trimmed.match(global);
  if (g) {
    const n = Number(g[1]);
    if (n >= 1 && n <= 9999) {
      return { periodKey: docPeriodKey(new Date()), seq: n };
    }
  }

  const d = trimmed.match(dated);
  if (d) {
    const n = Number(d[1]);
    if (Number.isFinite(n) && n >= 1) {
      return { periodKey: docPeriodKey(new Date()), seq: Math.min(n, DOC_SEQ_MAX) };
    }
  }

  return null;
}

export function parseDocNoSeq(
  value: string,
  prefix: string,
  periodKey?: string,
): number | null {
  const parts = parseDocNoParts(value, prefix);
  if (!parts) return null;
  if (periodKey && parts.periodKey !== periodKey) return null;
  return parts.seq;
}

/** True jika nomor mengikuti pola auto (bulanan atau legacy). */
export function isAutoGeneratedDocNo(
  value: string,
  prefix: string,
  periodDate?: string | Date,
): boolean {
  const trimmed = value.trim();
  if (!trimmed) return false;
  const parts = parseDocNoParts(trimmed, prefix);
  if (!parts) return false;
  if (periodDate) {
    return parts.periodKey === docPeriodKey(periodDate);
  }
  return true;
}

export function docNumberFormatHint(prefix: string): string {
  const pk = docPeriodKey(new Date());
  return `Format ${prefix}-${pk}-00001 … ${prefix}-${pk}-99999 (reset per bulan).`;
}

function nextSeqAfter(max: number): number {
  if (max >= DOC_SEQ_MAX) return 1;
  return max + 1;
}

async function findMaxSeq(config: NumberingConfig, periodKey: string): Promise<number> {
  let max = 0;
  const needle = `${config.prefix}-${periodKey}-`;
  try {
    const docPb = await resolveDocPb();
    const rows = await docPb.collection(config.collection).getFullList<Record<string, unknown>>({
      filter: `${config.field} ~ "${escapeFilter(needle)}"`,
      fields: config.field,
      requestKey: null,
    });
    for (const row of rows) {
      const val = row[config.field];
      if (typeof val !== "string") continue;
      const seq = parseDocNoSeq(val, config.prefix, periodKey);
      if (seq != null) max = Math.max(max, seq);
    }
  } catch {
    return 0;
  }
  return max;
}

/** Nomor urut berikutnya: PREFIX-MMYYYY-00001 … 99999, reset tiap bulan. */
export async function nextDocNo(
  config: NumberingConfig,
  opts?: DocNumberOpts,
): Promise<string> {
  const periodKey = docPeriodKey(opts?.periodDate ?? new Date());
  const max = await findMaxSeq(config, periodKey);
  let candidate = nextSeqAfter(max);

  for (let attempt = 0; attempt < DOC_SEQ_MAX; attempt++) {
    const docNo = formatDocNo(config.prefix, candidate, periodKey);
    if (!(await isDocNoTaken(config, docNo))) return docNo;
    candidate = nextSeqAfter(candidate);
  }

  throw new Error(
    `Semua nomor ${config.prefix}-${periodKey}-00001 s/d ${config.prefix}-${periodKey}-99999 sudah dipakai.`,
  );
}

export async function nextDocNoFor(
  kind: BizDocNumberKind,
  opts?: DocNumberOpts,
): Promise<string> {
  return nextDocNo(BIZ_DOC_NUMBER_CONFIG[kind], opts);
}

export async function isDocNoTaken(
  config: NumberingConfig,
  docNo: string,
  excludeId?: string,
): Promise<boolean> {
  const trimmed = docNo.trim();
  if (!trimmed) return false;
  let filter = `${config.field} = "${escapeFilter(trimmed)}"`;
  if (excludeId) filter += ` && id != "${escapeFilter(excludeId)}"`;
  try {
    const docPb = await resolveDocPb();
    const list = await docPb.collection(config.collection).getList(1, 1, {
      filter,
      requestKey: null,
    });
    return list.totalItems > 0;
  } catch {
    return false;
  }
}

export async function assertDocNoAvailable(
  config: NumberingConfig,
  docNo: string,
  excludeId?: string,
): Promise<void> {
  if (await isDocNoTaken(config, docNo, excludeId)) {
    throw new Error(`Nomor ${docNo.trim()} sudah dipakai. Pilih nomor lain.`);
  }
}

/** Ubah prefix dokumen — MMYYYY & urutan tetap (SO-062026-00019 → INV-062026-00019). */
export function pairedDocNo(value: string, targetPrefix: string): string | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  for (const prefix of [BIZ_DOC_NUMBER_CONFIG.so.prefix, BIZ_DOC_NUMBER_CONFIG.inv.prefix]) {
    const parts = parseDocNoParts(trimmed, prefix);
    if (parts) return formatDocNo(targetPrefix, parts.seq, parts.periodKey);
  }
  return null;
}

export function invoiceNoFromSalesOrder(orderNo: string): string | null {
  return pairedDocNo(orderNo, BIZ_DOC_NUMBER_CONFIG.inv.prefix);
}

export function salesOrderNoFromInvoice(invoiceNo: string): string | null {
  return pairedDocNo(invoiceNo, BIZ_DOC_NUMBER_CONFIG.so.prefix);
}

/**
 * Nomor invoice dari SO — urutan sama, hanya prefix INV.
 * Nomor SO eksternal (bukan format SO-MMYYYY-#####) → nomor invoice baru terpisah.
 */
export async function resolveInvoiceNoForSalesOrder(
  orderNo: string,
  opts?: { periodDate?: string | Date },
): Promise<string> {
  const paired = invoiceNoFromSalesOrder(orderNo);
  if (paired) {
    if (await isDocNoTaken(BIZ_DOC_NUMBER_CONFIG.inv, paired)) {
      throw new Error(`Nomor invoice pasangan ${paired} sudah dipakai.`);
    }
    return paired;
  }
  return nextDocNo(BIZ_DOC_NUMBER_CONFIG.inv, { periodDate: opts?.periodDate });
}
