import type PocketBase from "pocketbase";
import { isAutoGeneratedDocNo, BIZ_DOC_NUMBER_CONFIG } from "@/lib/bisnis/doc-number";
import { BISNIS_COLLECTIONS } from "@/lib/bisnis/types";

/** Huruf/angka tanpa karakter mudah tertukar (0/O, 1/I/L). */
const PICKUP_CHARSET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
const PICKUP_CODE_LEN = 8;

function escapeFilter(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function randomPickupBody(): string {
  let out = "";
  for (let i = 0; i < PICKUP_CODE_LEN; i++) {
    out += PICKUP_CHARSET[Math.floor(Math.random() * PICKUP_CHARSET.length)]!;
  }
  return out;
}

/** Kode pickup acak — 8 karakter; awalan "PK" hanya di UI, bukan bagian nomor. */
export function formatPickupCode(body: string): string {
  const clean = body.replace(/[^A-Za-z0-9]/g, "").toUpperCase().slice(0, PICKUP_CODE_LEN);
  return clean.padEnd(PICKUP_CODE_LEN, PICKUP_CHARSET[0]!);
}

export async function isPickupCodeTaken(pocket: PocketBase, code: string): Promise<boolean> {
  const esc = escapeFilter(code.trim());
  if (!esc) return false;
  try {
    const hit = await pocket.collection(BISNIS_COLLECTIONS.salesOrders).getList(1, 1, {
      filter: `(pk_no = "${esc}" || wms_booking_no = "${esc}") && status != "cancelled"`,
      fields: "id",
      requestKey: null,
    });
    if (hit.totalItems > 0) return true;
  } catch {
    /* SO schema / filter boleh gagal — lanjut cek retur */
  }
  try {
    const returHit = await pocket.collection(BISNIS_COLLECTIONS.returs).getList(1, 1, {
      filter: `resend_pickup_no = "${esc}" && status = "draft" && workflow_phase = "resend"`,
      fields: "id",
      requestKey: null,
    });
    return returHit.totalItems > 0;
  } catch {
    return false;
  }
}

/** Buat kode pickup unik — tidak berurutan seperti SO090726-0024. */
export async function generateUniquePickupCode(pocket: PocketBase): Promise<string> {
  for (let attempt = 0; attempt < 64; attempt++) {
    const code = formatPickupCode(randomPickupBody());
    if (!(await isPickupCodeTaken(pocket, code))) return code;
  }
  throw new Error("Gagal membuat kode pickup unik. Coba lagi.");
}

/**
 * Nomor pesanan manual (MP) → kode pickup = nomor itu.
 * SO otomatis (urut) → kode pickup acak agar tidak mudah ditebak di gudang.
 */
export async function resolvePickupCodeForPosOrder(
  pocket: PocketBase,
  orderNo: string,
  hasManualOrderNo: boolean,
): Promise<string> {
  if (hasManualOrderNo) return orderNo.trim();
  if (!isAutoGeneratedDocNo(orderNo, BIZ_DOC_NUMBER_CONFIG.so.prefix)) {
    return orderNo.trim();
  }
  return generateUniquePickupCode(pocket);
}
