"use client";

import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, Plus, Trash2, Loader2 } from "lucide-react";
import { pb } from "@/lib/pocketbase";
import {
  createPurchaseOrder,
  createPurchaseOrderLine,
  updatePurchaseOrder,
  updatePurchaseBill,
  deletePurchaseOrderLine,
  fetchPurchaseBill,
  fetchPurchaseOrder,
  fetchPurchaseOrderLines,
  fetchAllSuppliers,
  replaceAutoStockMovement,
  voidStockMovementsByReference,
  fetchStores,
  fetchTaxRates,
  fetchPaymentTerms,
  fetchPaymentMethods,
  fetchPurchaseBillByPurchaseOrder,
  canEditPurchaseOrder,
  sendPurchaseOrderToWarehouse,
} from "@/lib/bisnis/client";
import { canEditPurchaseBill } from "@/lib/bisnis/purchase-status";
import { updateProductBuyPrice } from "@/lib/inventory/client";
import type { Supplier, Store, TaxRate, PaymentTerm, PaymentMethodSetting } from "@/lib/bisnis/types";
import Link from "next/link";
import { NumSpinnerInput, fmtNum, parseNum } from "@/components/bisnis/NumSpinnerInput";
import { ShippingInfoSection, ShippingInfoToggle } from "@/components/bisnis/ShippingInfoSection";
import { onEnterFocusNext } from "@/lib/bisnis/form-nav";
import {
  buildNotesWithShipping,
  emptyShippingInfo,
  parseNotesWithShipping,
  type ShippingInfo,
} from "@/lib/bisnis/shipping-notes";
import {
  assertDocNoAvailable,
  BIZ_DOC_NUMBER_CONFIG,
  docNumberFormatHint,
  isAutoGeneratedDocNo,
  nextDocNoFor,
} from "@/lib/bisnis/doc-number";
import {
  parseReferenceFromNotes,
  prependReferenceToNotes,
} from "@/lib/bisnis/reference-notes";
import { getErrorMessage } from "@/lib/errors";
import { fetchWarehouseStockMap, getWarehouseStockQty } from "@/lib/bisnis/warehouse-stock";

const fmt = (v: number) =>
  new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(v);

type Product = { id: string; sku: string; name: string; buy_price?: number; unit?: string };

type LineItem = {
  product: string;
  description: string;
  qty: number;
  unit: string;
  unit_cost: number;
  discount_percent: number;
};

const emptyLine = (): LineItem => ({
  product: "", description: "", qty: 1, unit: "pcs", unit_cost: 0, discount_percent: 0,
});

const pickAddress = (supplier?: Supplier) =>
  [supplier?.address, supplier?.city].filter(Boolean).join(", ");

export default function BuatPembelianPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("edit");
  const poEditId = searchParams.get("po");
  const isEdit = !!editId;
  const isPoEdit = !!poEditId && !editId;

  const [editBillId, setEditBillId] = useState<string | null>(null);
  const [editPoId, setEditPoId] = useState<string | null>(null);
  const [editLineIds, setEditLineIds] = useState<string[]>([]);
  const [loadingEdit, setLoadingEdit] = useState(!!editId || !!poEditId);

  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [stores, setStores] = useState<Store[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [taxRates, setTaxRates] = useState<TaxRate[]>([]);
  const [paymentTerms, setPaymentTerms] = useState<PaymentTerm[]>([]);
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethodSetting[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [form, setForm] = useState({
    supplier: "",
    email: "",
    transaction_date: new Date().toISOString().slice(0, 10),
    due_date: "",
    transaction_no: "",
    ref_no: "",
    store: "",
    warehouse: "",
    payment_term: "",
    payment_method: "",
    message: "",
    memo: "",
    include_tax: false,
    tax_percent: 0,
    materai_amount: 0,
    send_to_warehouse: false,
  });

  const [lines, setLines] = useState<LineItem[]>([emptyLine()]);
  const [discountType, setDiscountType] = useState<"percent" | "amount">("percent");
  const [discountValue, setDiscountValue] = useState(0);
  const [stockMap, setStockMap] = useState<Record<string, number>>({});
  const [stockLoading, setStockLoading] = useState(false);
  const [shipping, setShipping] = useState<ShippingInfo>(emptyShippingInfo);

  useEffect(() => {
    if (!form.warehouse) {
      setStockMap({});
      return;
    }
    let cancelled = false;
    setStockLoading(true);
    fetchWarehouseStockMap(form.warehouse)
      .then((map) => {
        if (!cancelled) setStockMap(map);
      })
      .catch(() => {
        if (!cancelled) setStockMap({});
      })
      .finally(() => {
        if (!cancelled) setStockLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [form.warehouse]);

  useEffect(() => {
    if (isEdit) return;
    nextDocNoFor("po", { periodDate: form.transaction_date })
      .then((no) => {
        setForm((f) => {
          if (
            f.transaction_no &&
            !isAutoGeneratedDocNo(f.transaction_no, BIZ_DOC_NUMBER_CONFIG.po.prefix, f.transaction_date)
          ) {
            return f;
          }
          return { ...f, transaction_no: no };
        });
      })
      .catch(() => {});
  }, [isEdit, form.transaction_date]);

  useEffect(() => {
    Promise.all([
      fetchAllSuppliers(),
      fetchStores(),
      pb.collection("inv_products").getFullList<Product>({ sort: "name", requestKey: null }),
      fetchTaxRates().catch(() => [] as TaxRate[]),
      fetchPaymentTerms().catch(() => [] as PaymentTerm[]),
      fetchPaymentMethods().catch(() => [] as PaymentMethodSetting[]),
    ]).then(([s, st, p, tr, pt, pm]) => {
      setSuppliers(s);
      setStores(st);
      setProducts(p);
      setTaxRates(tr);
      setPaymentTerms(pt);
      setPaymentMethods(pm);
      if (st.length === 1) {
        setForm((f) => ({ ...f, store: st[0].id, warehouse: st[0].default_warehouse }));
      }
      const defaultTerm = pt.find((t) => t.is_default);
      if (defaultTerm) {
        const dd = new Date();
        dd.setDate(dd.getDate() + defaultTerm.days);
        setForm((f) => ({ ...f, payment_term: defaultTerm.id, due_date: dd.toISOString().slice(0, 10) }));
      }
      const defaultTax = tr.find((t) => t.is_default);
      if (defaultTax) setForm((f) => ({ ...f, tax_percent: defaultTax.rate }));
    }).catch(() => {});
  }, []);

  useEffect(() => {
    if (!poEditId || editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const poData = await fetchPurchaseOrder(poEditId);
        if (!canEditPurchaseOrder(poData)) {
          const linked = await fetchPurchaseBillByPurchaseOrder(poData.id);
          router.replace(linked ? `/bisnis/pembelian/${linked.id}` : `/bisnis/pembelian/${poData.id}`);
          return;
        }
        setEditPoId(poData.id);
        const poLines = await fetchPurchaseOrderLines(poEditId);
        setEditLineIds(poLines.map((l) => l.id));
        const { textNotes, shipping: ship } = parseNotesWithShipping(poData.notes ?? "");
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = body.split("\n");
        setShipping(ship);
        setForm((f) => ({
          ...f,
          supplier: poData.supplier,
          email: poData.expand?.supplier?.email ?? "",
          transaction_date: poData.order_date?.slice(0, 10) ?? f.transaction_date,
          due_date: poData.expected_date?.slice(0, 10) ?? "",
          transaction_no: poData.po_no,
          ref_no: reference,
          message: noteParts[0] ?? "",
          memo: noteParts.slice(1).join("\n"),
          send_to_warehouse: !!poData.send_to_warehouse_at,
        }));
        if (poLines.length > 0) {
          setLines(
            poLines.map((l) => ({
              product: l.product,
              description: l.expand?.product?.name ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_cost: l.unit_cost,
              discount_percent: 0,
            })),
          );
        }
        const wh = poData.warehouse;
        if (wh) {
          const store = stores.find((s) => s.default_warehouse === wh);
          setForm((f) => ({
            ...f,
            store: store?.id ?? f.store,
            warehouse: wh,
          }));
        }
        setProcessMode("po");
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Gagal memuat PO");
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [poEditId, editId, stores]);

  useEffect(() => {
    if (!editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const bill = await fetchPurchaseBill(editId);
        if (!canEditPurchaseBill(bill)) {
          setError("Pembelian dibatalkan tidak bisa diedit");
          return;
        }
        setEditBillId(bill.id);
        const poId = bill.purchase_order ?? null;
        setEditPoId(poId);
        const poLines = poId ? await fetchPurchaseOrderLines(poId) : [];
        setEditLineIds(poLines.map((l) => l.id));

        const rawNotes =
          bill.notes ?? bill.expand?.purchase_order?.notes ?? "";
        const { textNotes, shipping: ship } = parseNotesWithShipping(rawNotes);
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = body.split("\n");
        setShipping(ship);
        setForm((f) => ({
          ...f,
          supplier: bill.supplier,
          email: bill.expand?.supplier?.email ?? "",
          transaction_date: bill.bill_date?.slice(0, 10) ?? f.transaction_date,
          due_date: bill.due_date?.slice(0, 10) ?? "",
          transaction_no: bill.expand?.purchase_order?.po_no ?? bill.bill_no,
          ref_no: reference,
          materai_amount: bill.materai_amount ?? 0,
          message: noteParts[0] ?? "",
          memo: noteParts.slice(1).join("\n"),
          send_to_warehouse: !!bill.expand?.purchase_order?.send_to_warehouse_at,
        }));
        if (bill.expand?.supplier?.address) {
          setShipping((prev) => ({
            ...prev,
            recipient_address: prev.recipient_address || bill.expand?.supplier?.address || "",
          }));
        }

        if ((bill.discount_amount ?? 0) > 0) {
          setDiscountType("amount");
          setDiscountValue(bill.discount_amount ?? 0);
        }

        if (bill.tax_amount > 0 && bill.subtotal > 0) {
          const rate = Math.round((bill.tax_amount / (bill.subtotal - (bill.discount_amount ?? 0))) * 10000) / 100;
          setForm((f) => ({ ...f, tax_percent: rate }));
        }

        if (poLines.length > 0) {
          setLines(
            poLines.map((l) => ({
              product: l.product,
              description: l.expand?.product?.name ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_cost: l.unit_cost,
              discount_percent: 0,
            })),
          );
        }

        const wh = bill.expand?.purchase_order?.warehouse;
        if (wh) {
          const store = stores.find((s) => s.default_warehouse === wh);
          if (store) {
            setForm((f) => ({ ...f, store: store.id, warehouse: wh }));
          } else {
            setForm((f) => ({ ...f, warehouse: wh }));
          }
        }
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Gagal memuat data edit");
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [editId, stores]);

  const selectSupplier = (id: string) => {
    const sup = suppliers.find((s) => s.id === id);
    setForm((f) => ({ ...f, supplier: id, email: sup?.email ?? "" }));
    setShipping((s) => ({ ...s, recipient_address: pickAddress(sup) || s.recipient_address }));
  };

  const updateLine = (idx: number, field: keyof LineItem, value: string | number) => {
    setLines((prev) => {
      const next = [...prev];
      if (field === "product") {
        const prod = products.find((p) => p.id === value);
        next[idx] = {
          ...next[idx],
          product: value as string,
          unit: prod?.unit ?? "pcs",
          unit_cost: prod?.buy_price ?? next[idx].unit_cost,
        };
      } else {
        (next[idx] as Record<string, unknown>)[field] = value;
      }
      return next;
    });
  };

  const addLine = () => setLines((prev) => [...prev, emptyLine()]);
  const removeLine = (idx: number) => setLines((prev) => (prev.length <= 1 ? prev : prev.filter((_, i) => i !== idx)));

  const calcLineTotal = (l: LineItem) => {
    const gross = l.qty * l.unit_cost;
    return gross - gross * (l.discount_percent / 100);
  };

  const subtotal = lines.reduce((s, l) => s + calcLineTotal(l), 0);
  const extraDiscount = discountType === "percent" ? subtotal * (discountValue / 100) : discountValue;
  const afterDiscount = subtotal - extraDiscount;
  const totalTax = form.include_tax
    ? (afterDiscount * form.tax_percent) / (100 + form.tax_percent || 1)
    : afterDiscount * (form.tax_percent / 100);
  const taxExclusiveSubtotal = form.include_tax ? afterDiscount - totalTax : afterDiscount;
  const shippingCost = shipping.enabled ? Math.max(0, shipping.shipping_cost || 0) : 0;
  const materai = form.materai_amount || 0;
  const grandTotal = taxExclusiveSubtotal + totalTax + shippingCost + materai;
  const handleSubmit = async () => {
    if (!form.supplier) { setError("Supplier wajib dipilih"); return; }
    if (!form.store || !form.warehouse) { setError("Toko wajib dipilih (gudang default akan dipakai untuk stok masuk)"); return; }
    if (lines.every((l) => !l.product)) { setError("Tambahkan minimal 1 produk"); return; }

    setSubmitting(true);
    setError(null);
    try {
      const validLines = lines.filter((l) => l.product);
      const userId = pb.authStore.model?.id as string;
      const term = paymentTerms.find((t) => t.id === form.payment_term);
      const isCash =
        !form.payment_term ||
        (term?.days ?? 0) === 0 ||
        !form.due_date ||
        form.due_date.slice(0, 10) === form.transaction_date.slice(0, 10);
      const txNo = form.transaction_no.trim();
      if (!txNo) {
        setError("Nomor PO belum tersedia, coba simpan ulang.");
        return;
      }
      if (!isEdit) {
        await assertDocNoAvailable(
          BIZ_DOC_NUMBER_CONFIG.po,
          txNo,
          isPoEdit ? (editPoId ?? undefined) : undefined,
        );
      }
      const textNotes = [form.message, form.memo].filter(Boolean).join("\n");
      const notesWithRef = prependReferenceToNotes(textNotes, form.ref_no);
      const notes = buildNotesWithShipping(notesWithRef, shipping);

      if (isPoEdit && editPoId) {
        const linked = await fetchPurchaseBillByPurchaseOrder(editPoId);
        if (linked) {
          setError(`PO sudah punya tagihan ${linked.bill_no}. Edit lewat halaman tagihan.`);
          return;
        }

        const updatedPo = await updatePurchaseOrder(editPoId, {
          supplier: form.supplier,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          expected_date: form.due_date || undefined,
          status: "draft",
          notes,
          subtotal,
          tax_amount: totalTax,
          total: grandTotal,
        });

        await Promise.all(editLineIds.map((lid) => deletePurchaseOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createPurchaseOrderLine({
              purchase_order: editPoId,
              product: l.product,
              qty: l.qty,
              received_qty: 0,
              unit_cost: l.unit_cost,
              line_total: calcLineTotal(l),
            }),
          ),
        );
        if (form.send_to_warehouse && !updatedPo.send_to_warehouse_at) {
          await sendPurchaseOrderToWarehouse(editPoId, userId);
        }

        router.push(`/bisnis/pembelian/${editPoId}`);
        return;
      }

      if (isEdit && editBillId && editPoId) {
        const existingBill = await fetchPurchaseBill(editBillId);
        const paidKeep = isCash ? grandTotal : (existingBill.paid_amount ?? 0);

        await updatePurchaseOrder(editPoId, {
          supplier: form.supplier,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          expected_date: form.due_date || undefined,
          status: "received",
          notes,
          subtotal,
          tax_amount: totalTax,
          total: grandTotal,
        });

        await Promise.all(editLineIds.map((lid) => deletePurchaseOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createPurchaseOrderLine({
              purchase_order: editPoId,
              product: l.product,
              qty: l.qty,
              received_qty: l.qty,
              unit_cost: l.unit_cost,
              line_total: calcLineTotal(l),
            }),
          ),
        );

        await updatePurchaseBill(editBillId, {
          supplier: form.supplier,
          bill_date: form.transaction_date,
          due_date: isCash ? form.transaction_date : form.due_date || form.transaction_date,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
          paid_amount: paidKeep,
          remaining: isCash ? 0 : Math.max(0, grandTotal - paidKeep),
          status: isCash ? "paid" : "unpaid",
          is_cash: isCash,
          notes,
        });

        if (form.warehouse && validLines.length > 0) {
          await replaceAutoStockMovement({
            type: "PURCHASE",
            warehouse: form.warehouse,
            reference_type: "PURCHASE_ORDER",
            reference_id: editPoId,
            reference_no: txNo,
            lines: validLines.map((l) => ({ product: l.product, qty: l.qty })),
            voidNote: `Edit pembelian ${txNo}`,
          });
        } else if (editPoId) {
          await voidStockMovementsByReference(
            {
              referenceId: editPoId,
              referenceType: "PURCHASE_ORDER",
              referenceNo: txNo,
            },
            "Edit pembelian tanpa baris",
          );
        }

        await Promise.all(
          validLines.map((l) => updateProductBuyPrice(l.product, l.unit_cost).catch(() => {})),
        );

        router.push(`/bisnis/pembelian/${editBillId}`);
        return;
      }

      const po = await createPurchaseOrder({
        po_no: txNo,
        supplier: form.supplier,
        warehouse: form.warehouse,
        order_date: form.transaction_date,
        expected_date: form.due_date || undefined,
        status: "draft",
        notes,
        created_by: userId,
        subtotal,
        tax_amount: totalTax,
        total: grandTotal,
      });

      await Promise.all(
        validLines.map((l) =>
          createPurchaseOrderLine({
            purchase_order: po.id,
            product: l.product,
            qty: l.qty,
            received_qty: 0,
            unit_cost: l.unit_cost,
            line_total: calcLineTotal(l),
          }),
        ),
      );

      if (form.send_to_warehouse) {
        await sendPurchaseOrderToWarehouse(po.id, userId);
      }

      router.push(`/bisnis/pembelian/${po.id}`);
    } catch (e: unknown) {
      setError(getErrorMessage(e, "Gagal menyimpan pembelian"));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen">
      <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Link href="/bisnis/pembelian" className="mb-1 inline-flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-700">
            <ArrowLeft className="h-3.5 w-3.5" /> Pembelian
          </Link>
          <h1 className="text-xl font-bold text-slate-900">
            {isEdit ? "Edit Pembelian" : isPoEdit ? "Edit PO" : "Buat Pembelian"}
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Stok masuk ke gudang default toko — saldo real-time dari pembelian/penjualan yang sudah diposting
          </p>
          {!isEdit && !isPoEdit && (
            <p className="mt-2 text-xs text-amber-800">
              Simpan sebagai <strong>Purchase Order</strong> saja. Tagihan (BILL) dibuat manual dari detail PO.
              Tanpa WMS: tagihan kapan saja. Lewat WMS: tagihan setelah gudang <strong>Komplit</strong>.
            </p>
          )}
          <label className="mt-2 inline-flex items-center gap-2 text-xs text-slate-700">
            <input
              type="checkbox"
              checked={form.send_to_warehouse}
              onChange={(e) => setForm((f) => ({ ...f, send_to_warehouse: e.target.checked }))}
              className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            Lewat gudang (WMS) — penerimaan: kirim ke antrean Penerimaan (gudang masuk = gudang di PO)
          </label>
        </div>
        <div className="text-right">
          <span className="text-sm text-slate-500">Total</span>
          <div className="text-xl font-bold text-slate-900">{fmt(grandTotal)}</div>
        </div>
      </div>

      {loadingEdit && (
        <div className="mb-4 flex items-center gap-2 text-sm text-slate-500">
          <Loader2 className="h-4 w-4 animate-spin text-indigo-600" />
          Memuat data pembelian…
        </div>
      )}

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 whitespace-pre-line">
          {error}
        </div>
      )}

      <div className="rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-100 px-6 py-5">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Supplier <span className="text-red-500">*</span></label>
              <select data-nav value={form.supplier} onChange={(e) => selectSupplier(e.target.value)} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih supplier</option>
                {suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              {form.supplier && (
                <p className="mt-1 text-xs text-slate-500">
                  Alamat supplier (master):{" "}
                  <span className="font-medium text-slate-700">
                    {pickAddress(suppliers.find((s) => s.id === form.supplier)) || "—"}
                  </span>
                </p>
              )}
            </div>
            <div>
              <div className="mb-1 flex items-center justify-between gap-2">
                <label className="text-sm font-medium text-slate-700">Email</label>
                <ShippingInfoToggle shipping={shipping} onChange={setShipping} />
              </div>
              <input data-nav type="email" value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Tgl. transaksi</label>
              <input data-nav type="date" value={form.transaction_date} onChange={(e) => setForm((f) => ({ ...f, transaction_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">No. PO</label>
              <input data-nav type="text" value={form.transaction_no} onChange={(e) => setForm((f) => ({ ...f, transaction_no: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-sm font-mono text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
              <p className="mt-1 text-xs text-slate-500">{docNumberFormatHint("PO")}</p>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">No. referensi</label>
              <input
                data-nav
                type="text"
                value={form.ref_no}
                onChange={(e) => setForm((f) => ({ ...f, ref_no: e.target.value }))}
                onKeyDown={onEnterFocusNext}
                placeholder="Faktur supplier, SJ, dll."
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
              />
            </div>
          </div>
          {shipping.enabled && (
            <div className="mt-4">
              <ShippingInfoSection shipping={shipping} onChange={setShipping} showToggle={false} />
              <p className="mt-2 text-xs text-slate-500">
                Alamat penerima default diambil dari master supplier, namun tetap bisa diubah per transaksi.
              </p>
            </div>
          )}
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Term Pembayaran</label>
              <select data-nav value={form.payment_term} onKeyDown={onEnterFocusNext} onChange={(e) => {
                const termId = e.target.value;
                const t = paymentTerms.find((x) => x.id === termId);
                if (t) {
                  const dd = new Date(form.transaction_date || Date.now());
                  dd.setDate(dd.getDate() + t.days);
                  setForm((f) => ({ ...f, payment_term: termId, due_date: dd.toISOString().slice(0, 10) }));
                } else {
                  setForm((f) => ({ ...f, payment_term: "" }));
                }
              }}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih term</option>
                {paymentTerms.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Tgl. jatuh tempo</label>
              <input data-nav type="date" value={form.due_date} onChange={(e) => setForm((f) => ({ ...f, due_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Metode pembayaran</label>
              <select data-nav value={form.payment_method} onChange={(e) => setForm((f) => ({ ...f, payment_method: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">{paymentMethods.length === 0 ? "— Belum ada metode" : "Pilih metode"}</option>
                {paymentMethods.map((m) => <option key={m.id} value={m.code || m.name}>{m.name}</option>)}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Toko <span className="text-red-500">*</span></label>
              <select data-nav value={form.store} onKeyDown={onEnterFocusNext} onChange={(e) => {
                const storeId = e.target.value;
                const selectedStore = stores.find((s) => s.id === storeId);
                setForm((f) => ({ ...f, store: storeId, warehouse: selectedStore?.default_warehouse || "" }));
              }}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih toko</option>
                {stores.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              {form.store && (
                <p className="mt-1 text-xs text-slate-400">
                  Gudang: <span className="font-medium text-slate-600">{stores.find((s) => s.id === form.store)?.expand?.default_warehouse?.name || form.warehouse || "—"}</span>
                  {form.warehouse && (
                    <span className="ml-2 text-slate-500">
                      {stockLoading ? "· memuat stok…" : "· saldo inv_stock_balances (Stok Global)"}
                      <Link
                        href={`/gudang/stok?warehouse=${encodeURIComponent(form.warehouse)}`}
                        className="ml-2 font-medium text-indigo-600 hover:underline"
                      >
                        Lihat stok gudang →
                      </Link>
                    </span>
                  )}
                </p>
              )}
              {form.store && !form.warehouse && (
                <p className="mt-1 text-xs font-medium text-red-600">
                  Toko ini belum punya gudang default. Atur di Bisnis → Toko.
                </p>
              )}
            </div>
          </div>
          <div className="mt-3 flex items-center justify-end">
            <label className="flex cursor-pointer items-center gap-2 text-sm text-slate-600">
              <input
                type="checkbox"
                checked={form.include_tax}
                onChange={(e) => setForm((f) => ({ ...f, include_tax: e.target.checked }))}
                className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
              />
              Harga termasuk pajak
            </label>
          </div>
        </div>

        <div className="overflow-x-auto overflow-y-visible">
          <table className="w-full table-fixed text-sm">
            <colgroup>
              <col className="w-[34%]" />
              <col className="w-[12%]" />
              <col className="w-[8%]" />
              <col className="w-[8%]" />
              <col className="w-[14%]" />
              <col className="w-[8%]" />
              <col className="w-[14%]" />
              <col className="w-[2%]" />
            </colgroup>
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-left">
                <th className="px-3 py-3 text-xs font-semibold text-slate-600">Produk</th>
                <th className="px-2 py-3 text-xs font-semibold text-slate-600">Catatan</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Qty beli</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Unit</th>
                <th className="px-2 py-3 text-right text-xs font-semibold text-slate-600">Harga beli</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Diskon</th>
                <th className="px-2 py-3 text-right text-xs font-semibold text-slate-600">Jumlah</th>
                <th className="px-1 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {lines.map((line, idx) => (
                <tr key={idx} className="group align-top">
                  <td className="px-3 py-2">
                    <select data-nav value={line.product} onChange={(e) => updateLine(idx, "product", e.target.value)} onKeyDown={onEnterFocusNext}
                      title={
                        line.product
                          ? (() => {
                              const p = products.find((x) => x.id === line.product);
                              if (!p) return undefined;
                              const st = getWarehouseStockQty(stockMap, p.id);
                              return `${p.name} · stok ${fmtNum(st)}`;
                            })()
                          : undefined
                      }
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-sm">
                      <option value="">Pilih produk</option>
                      {products.map((p) => {
                        const st = getWarehouseStockQty(stockMap, p.id);
                        return (
                          <option key={p.id} value={p.id}>
                            {p.name} · stok {fmtNum(st)}
                          </option>
                        );
                      })}
                    </select>
                  </td>
                  <td className="px-2 py-2">
                    <input data-nav type="text" value={line.description} onChange={(e) => updateLine(idx, "description", e.target.value)} onKeyDown={onEnterFocusNext}
                      placeholder="Catatan" className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-sm" />
                  </td>
                  <td className="px-2 py-2">
                    <NumSpinnerInput data-nav value={line.qty} min={1} onChange={(v) => updateLine(idx, "qty", v)} inputClassName="w-full min-w-0 text-center text-sm" />
                  </td>
                  <td className="px-2 py-2">
                    <input data-nav type="text" value={line.unit} onChange={(e) => updateLine(idx, "unit", e.target.value)} onKeyDown={onEnterFocusNext}
                      className="w-full min-w-0 rounded border border-slate-200 px-1.5 py-1.5 text-center text-sm text-slate-700 focus:border-indigo-400 focus:outline-none" />
                  </td>
                  <td className="px-2 py-2">
                    <input data-nav type="text" inputMode="numeric" value={line.unit_cost ? fmtNum(line.unit_cost) : ""}
                      onChange={(e) => updateLine(idx, "unit_cost", Math.max(0, parseNum(e.target.value)))} onKeyDown={onEnterFocusNext}
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-right text-sm" />
                  </td>
                  <td className="px-2 py-2">
                    <NumSpinnerInput data-nav value={line.discount_percent} min={0} max={100} suffix="%" onChange={(v) => updateLine(idx, "discount_percent", v)} inputClassName="w-full min-w-0 text-center text-sm" />
                  </td>
                  <td className="px-2 py-2 text-right text-sm font-medium whitespace-nowrap">{fmt(calcLineTotal(line))}</td>
                  <td className="px-2 py-2">
                    <button type="button" onClick={() => removeLine(idx)} className="rounded p-1 text-slate-300 opacity-0 group-hover:opacity-100 hover:text-red-500">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="border-t border-slate-100 px-4 py-3">
          <button type="button" onClick={addLine} className="inline-flex items-center gap-1 text-sm font-medium text-indigo-600">
            <Plus className="h-4 w-4" /> Tambah baris
          </button>
        </div>

        <div className="grid grid-cols-1 border-t border-slate-200 lg:grid-cols-2">
          <div className="border-b border-slate-200 p-6 lg:border-b-0 lg:border-r">
            <textarea data-nav rows={2} value={form.message} onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))} placeholder="Pesan"
              className="mb-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" />
            <textarea data-nav rows={2} value={form.memo} onChange={(e) => setForm((f) => ({ ...f, memo: e.target.value }))} placeholder="Memo"
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" />
          </div>
          <div className="p-6 space-y-2 text-sm">
            <div className="flex justify-between"><span>Subtotal</span><span className="font-medium">{fmt(subtotal)}</span></div>
            <div className="flex items-center justify-between gap-2">
              <span>PPN / Pajak</span>
              <div className="flex items-center gap-2">
                <select value={form.tax_percent} onChange={(e) => setForm((f) => ({ ...f, tax_percent: Number(e.target.value) }))}
                  className="rounded border border-slate-200 px-2 py-0.5 text-xs">
                  <option value={0}>Tanpa Pajak</option>
                  {taxRates.map((t) => <option key={t.id} value={t.rate}>{t.name}</option>)}
                </select>
                {form.include_tax && (
                  <span className="text-[11px] font-medium text-indigo-600">included</span>
                )}
              </div>
              <span>{fmt(totalTax)}</span>
            </div>
            <div className="flex justify-between items-center gap-2">
              <span>Biaya Materai</span>
              <input type="text" inputMode="numeric" value={form.materai_amount ? fmtNum(form.materai_amount) : ""}
                onChange={(e) => setForm((f) => ({ ...f, materai_amount: Math.max(0, parseNum(e.target.value)) }))}
                className="w-28 rounded border border-slate-200 px-2 py-0.5 text-right text-xs" />
            </div>
            {shippingCost > 0 && (
              <div className="flex justify-between">
                <span>Ongkir</span>
                <span>{fmt(shippingCost)}</span>
              </div>
            )}
            <div className="flex justify-between border-t pt-2 font-bold"><span>Total</span><span>{fmt(grandTotal)}</span></div>
          </div>
        </div>

        <div className="flex justify-end gap-3 border-t border-slate-200 px-6 py-4">
          <Link href="/bisnis/pembelian" className="rounded-lg border border-slate-300 px-5 py-2.5 text-sm font-medium text-slate-700 hover:bg-slate-50">Batal</Link>
          <button type="button" data-nav onClick={handleSubmit} disabled={submitting}
            className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50">
            {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
            {isEdit || isPoEdit ? "Simpan Perubahan" : "Simpan PO"}
          </button>
        </div>
      </div>
    </div>
  );
}
