"use client";

import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, Plus, Trash2, Loader2 } from "lucide-react";
import { pb } from "@/lib/pocketbase";
import {
  createSalesOrder, createSalesOrderLine, updateSalesOrder, updateInvoice,
  fetchInvoice, fetchSalesOrderLines, deleteSalesOrderLine,
  fetchAllCustomers, createCustomer,
  createAutoStockMovement,
  voidStockMovementsByReference,
  fetchStores,
  fetchTaxRates,
  fetchPaymentTerms,
  fetchPaymentMethods,
  fetchSalesOrder,
  fetchInvoiceBySalesOrder,
  canEditSalesOrder,
  sendSalesOrderToWarehouse,
} from "@/lib/bisnis/client";
import { canEditInvoice } from "@/lib/bisnis/invoice-status";
import { validateStockForSale } from "@/lib/bisnis/stock-check";
import { fetchWarehouseStockMap, getWarehouseStockQty } from "@/lib/bisnis/warehouse-stock";
import type { Customer, Store, TaxRate, PaymentTerm, PaymentMethodSetting } from "@/lib/bisnis/types";
import Link from "next/link";
import { NumSpinnerInput, fmtNum, parseNum } from "@/components/bisnis/NumSpinnerInput";
import { ShippingInfoSection, ShippingInfoToggle } from "@/components/bisnis/ShippingInfoSection";
import { onEnterFocusNext } from "@/lib/bisnis/form-nav";
import {
  buildNotesWithShipping,
  emptyShippingInfo,
  parseNotesWithShipping,
  type ShippingInfo,
} from "@/lib/bisnis/shipping-notes";
import {
  appendBankTransferToNotes,
  emptyBankTransferInfo,
  parseNotesWithBankTransfer,
  type BankTransferInfo,
} from "@/lib/bisnis/bank-transfer-notes";
import {
  assertDocNoAvailable,
  BIZ_DOC_NUMBER_CONFIG,
  docNumberFormatHint,
  isAutoGeneratedDocNo,
  nextDocNoFor,
} from "@/lib/bisnis/doc-number";
import {
  parseReferenceFromNotes,
  prependReferenceToNotes,
} from "@/lib/bisnis/reference-notes";

const fmt = (v: number) =>
  new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(v);

type Product = { id: string; sku: string; name: string; sell_price?: number; unit?: string };

type LineItem = {
  product: string;
  description: string;
  qty: number;
  unit: string;
  unit_price: number;
  discount_percent: number;
};

const emptyLine = (): LineItem => ({
  product: "", description: "", qty: 1, unit: "pcs", unit_price: 0, discount_percent: 0,
});

export default function BuatPenjualanPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("edit");
  const soEditId = searchParams.get("so");
  const isEdit = !!editId;
  const isSoEdit = !!soEditId && !editId;

  const [editInvoiceId, setEditInvoiceId] = useState<string | null>(null);
  const [editSoId, setEditSoId] = useState<string | null>(null);
  const [editLineIds, setEditLineIds] = useState<string[]>([]);
  const [loadingEdit, setLoadingEdit] = useState(!!editId || !!soEditId);

  const [customers, setCustomers] = useState<Customer[]>([]);
  const [stores, setStores] = useState<Store[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [taxRates, setTaxRates] = useState<TaxRate[]>([]);
  const [paymentTerms, setPaymentTerms] = useState<PaymentTerm[]>([]);
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethodSetting[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [form, setForm] = useState({
    customer: "",
    customer_name: "",
    email: "",
    transaction_date: new Date().toISOString().slice(0, 10),
    due_date: "",
    transaction_no: "",
    ref_no: "",
    store: "",
    warehouse: "",
    payment_term: "",
    payment_method: "",
    message: "",
    memo: "",
    include_tax: false,
    tax_percent: 0,
    materai_amount: 0,
    send_to_warehouse: false,
  });

  const [lines, setLines] = useState<LineItem[]>([emptyLine()]);
  const [discountType, setDiscountType] = useState<"percent" | "amount">("percent");
  const [discountValue, setDiscountValue] = useState(0);
  const [stockMap, setStockMap] = useState<Record<string, number>>({});
  const [stockLoading, setStockLoading] = useState(false);
  const [shipping, setShipping] = useState<ShippingInfo>(emptyShippingInfo);
  const [transferInfo, setTransferInfo] = useState<BankTransferInfo>(emptyBankTransferInfo);

  const selectedStore = stores.find((s) => s.id === form.store);
  const isCashMethod = /cash|tunai/i.test(form.payment_method || "");

  useEffect(() => {
    if (!form.warehouse) {
      setStockMap({});
      return;
    }
    let cancelled = false;
    setStockLoading(true);
    fetchWarehouseStockMap(form.warehouse)
      .then((map) => {
        if (!cancelled) setStockMap(map);
      })
      .catch(() => {
        if (!cancelled) setStockMap({});
      })
      .finally(() => {
        if (!cancelled) setStockLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [form.warehouse]);

  useEffect(() => {
    if (isEdit) return;
    nextDocNoFor("so", { periodDate: form.transaction_date })
      .then((no) => {
        setForm((f) => {
          if (
            f.transaction_no &&
            !isAutoGeneratedDocNo(f.transaction_no, BIZ_DOC_NUMBER_CONFIG.so.prefix, f.transaction_date)
          ) {
            return f;
          }
          return { ...f, transaction_no: no };
        });
      })
      .catch(() => {});
  }, [isEdit, form.transaction_date]);

  useEffect(() => {
    Promise.all([
      fetchAllCustomers(),
      fetchStores(),
      pb.collection("inv_products").getFullList<Product>({ sort: "name", requestKey: null }),
      fetchTaxRates().catch(() => [] as TaxRate[]),
      fetchPaymentTerms().catch(() => [] as PaymentTerm[]),
      fetchPaymentMethods().catch(() => [] as PaymentMethodSetting[]),
    ]).then(([c, s, p, tr, pt, pm]) => {
      setCustomers(c);
      setStores(s);
      setProducts(p);
      setTaxRates(tr);
      setPaymentTerms(pt);
      setPaymentMethods(pm);
      if (s.length === 1) {
        setForm((f) => ({ ...f, store: s[0].id, warehouse: s[0].default_warehouse }));
      }
      const defaultTerm = pt.find((t) => t.is_default);
      if (defaultTerm) {
        const dd = new Date();
        dd.setDate(dd.getDate() + defaultTerm.days);
        setForm((f) => ({ ...f, due_date: dd.toISOString().slice(0, 10) }));
      }
      const defaultTax = tr.find((t) => t.is_default);
      if (defaultTax) {
        setForm((f) => ({ ...f, tax_percent: defaultTax.rate }));
      }
    }).catch(() => {});
  }, []);

  useEffect(() => {
    if (!soEditId || editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const soData = await fetchSalesOrder(soEditId);
        if (!canEditSalesOrder(soData)) {
          const linked = await fetchInvoiceBySalesOrder(soData.id);
          router.replace(linked ? `/bisnis/penjualan/${linked.id}` : `/bisnis/penjualan/${soData.id}`);
          return;
        }
        setEditSoId(soData.id);
        const soLines = await fetchSalesOrderLines(soEditId);
        setEditLineIds(soLines.map((l) => l.id));
        const rawNotes = soData.notes ?? "";
        const { textNotes: notesNoBank, bank } = parseNotesWithBankTransfer(rawNotes);
        const { textNotes, shipping: ship } = parseNotesWithShipping(notesNoBank);
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = body.split("\n");
        setShipping(ship);
        setTransferInfo(bank);
        setForm((f) => ({
          ...f,
          customer: soData.customer,
          customer_name: soData.expand?.customer?.name ?? "",
          email: soData.expand?.customer?.email ?? "",
          transaction_date: soData.order_date?.slice(0, 10) ?? f.transaction_date,
          due_date: soData.due_date?.slice(0, 10) ?? "",
          transaction_no: soData.order_no,
          ref_no: reference,
          payment_method: soData.payment_method ?? "",
          materai_amount: soData.materai_amount ?? 0,
          send_to_warehouse: !!soData.send_to_warehouse_at,
          message: noteParts[0] ?? "",
          memo: noteParts.slice(1).join("\n"),
        }));
        if (soLines.length > 0) {
          setLines(
            soLines.map((l) => ({
              product: l.product,
              description: l.name_snapshot ?? l.expand?.product?.name ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_price: l.unit_price,
              discount_percent: l.discount_percent,
            })),
          );
        }
        if (soData.warehouse) {
          const store = stores.find((s) => s.default_warehouse === soData.warehouse);
          setForm((f) => ({ ...f, store: store?.id ?? f.store, warehouse: soData.warehouse }));
        }
        setProcessMode("so");
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Gagal memuat SO");
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [soEditId, editId, stores]);

  useEffect(() => {
    if (!editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const inv = await fetchInvoice(editId);
        if (!canEditInvoice(inv)) {
          setError("Invoice dibatalkan tidak bisa diedit");
          return;
        }
        setEditInvoiceId(inv.id);
        setEditSoId(inv.sales_order ?? null);
        const soLines = inv.sales_order ? await fetchSalesOrderLines(inv.sales_order) : [];
        setEditLineIds(soLines.map((l) => l.id));
        const rawNotes = inv.notes ?? inv.expand?.sales_order?.notes ?? "";
        const { textNotes: notesNoBank, bank } = parseNotesWithBankTransfer(rawNotes);
        const { textNotes, shipping: ship } = parseNotesWithShipping(notesNoBank);
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = body.split("\n");
        setShipping(ship);
        setTransferInfo(bank);
        setForm((f) => ({
          ...f,
          customer: inv.customer,
          customer_name: inv.expand?.customer?.name ?? "",
          email: inv.expand?.customer?.email ?? "",
          transaction_date: inv.issue_date?.slice(0, 10) ?? f.transaction_date,
          due_date: inv.due_date?.slice(0, 10) ?? "",
          transaction_no: inv.expand?.sales_order?.order_no ?? inv.invoice_no,
          ref_no: reference || inv.mp_order_no || "",
          materai_amount: inv.materai_amount ?? 0,
          send_to_warehouse: !!inv.expand?.sales_order?.send_to_warehouse_at,
          message: noteParts[0] ?? "",
          memo: noteParts.slice(1).join("\n"),
        }));
        if (inv.expand?.customer?.address) {
          setShipping((prev) => ({ ...prev, recipient_address: inv.expand?.customer?.address ?? prev.recipient_address }));
        }
        if (soLines.length > 0) {
          setLines(
            soLines.map((l) => ({
              product: l.product,
              description: l.name_snapshot ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_price: l.unit_price,
              discount_percent: l.discount_percent,
            })),
          );
        }
        const so = inv.expand?.sales_order;
        if (so?.warehouse) {
          const store = stores.find((s) => s.default_warehouse === so.warehouse);
          if (store) setForm((f) => ({ ...f, store: store.id, warehouse: so.warehouse }));
        }
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Gagal memuat data edit");
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [editId, stores]);

  useEffect(() => {
    const term = paymentTerms.find((t) => t.id === form.payment_term);
    const days = term?.days ?? 0;
    const isCashLike = days === 0 || !form.due_date || form.due_date === form.transaction_date;
    const bank_name = selectedStore?.bank_name ?? "";
    const account_name = selectedStore?.bank_account_name ?? "";
    const account_number = selectedStore?.bank_account_number ?? "";
    const hasBank = !!(bank_name && account_number);
    setTransferInfo((prev) => ({
      enabled: isCashLike ? false : (prev.enabled || hasBank),
      bank_name,
      account_name,
      account_number,
    }));
  }, [form.payment_term, form.due_date, form.transaction_date, selectedStore, paymentTerms]);

  useEffect(() => {
    if (isCashMethod) {
      setTransferInfo((prev) => ({ ...prev, enabled: false }));
    }
  }, [isCashMethod]);

  const selectCustomer = (id: string) => {
    const cust = customers.find((c) => c.id === id);
    setForm((f) => ({
      ...f,
      customer: id,
      customer_name: cust?.name ?? "",
      email: cust?.email ?? "",
    }));
    setShipping((s) => ({ ...s, recipient_address: cust?.address ?? s.recipient_address }));
  };

  const updateLine = (idx: number, field: keyof LineItem, value: string | number) => {
    setLines((prev) => {
      const next = [...prev];
      if (field === "product") {
        const prod = products.find((p) => p.id === value);
        next[idx] = {
          ...next[idx],
          product: value as string,
          unit_price: prod?.sell_price ?? next[idx].unit_price,
          unit: prod?.unit ?? "pcs",
        };
      } else {
        (next[idx] as Record<string, unknown>)[field] = value;
      }
      return next;
    });
  };

  const addLine = () => setLines((prev) => [...prev, emptyLine()]);
  const removeLine = (idx: number) => setLines((prev) => prev.length <= 1 ? prev : prev.filter((_, i) => i !== idx));

  const calcLineTotal = (l: LineItem) => {
    const gross = l.qty * l.unit_price;
    const disc = gross * (l.discount_percent / 100);
    return gross - disc;
  };

  const subtotal = lines.reduce((s, l) => s + calcLineTotal(l), 0);
  const lineDiscount = lines.reduce((s, l) => s + l.qty * l.unit_price * (l.discount_percent / 100), 0);
  const extraDiscount = discountType === "percent" ? subtotal * (discountValue / 100) : discountValue;
  const afterDiscount = subtotal - extraDiscount;
  const totalTax = form.include_tax
    ? (afterDiscount * form.tax_percent) / (100 + form.tax_percent || 1)
    : afterDiscount * (form.tax_percent / 100);
  const taxExclusiveSubtotal = form.include_tax ? afterDiscount - totalTax : afterDiscount;
  const shippingCost = shipping.enabled ? Math.max(0, shipping.shipping_cost || 0) : 0;
  const materai = form.materai_amount || 0;
  const grandTotal = taxExclusiveSubtotal + totalTax + shippingCost + materai;
  const handleSubmit = async () => {
    if (!form.customer && !form.customer_name.trim()) { setError("Pelanggan wajib dipilih / diisi"); return; }
    if (!form.store || !form.warehouse) { setError("Toko wajib dipilih"); return; }
    if (lines.every((l) => !l.product)) { setError("Tambahkan minimal 1 produk"); return; }

    setSubmitting(true);
    setError(null);
    try {
      let customerId = form.customer;
      if (!customerId && form.customer_name.trim()) {
        const customerSlug =
          form.customer_name
            .trim()
            .toUpperCase()
            .replace(/[^A-Z0-9]+/g, "")
            .slice(0, 8) || "BARU";
        const soSuffix =
          form.transaction_no
            .trim()
            .toUpperCase()
            .replace(/[^A-Z0-9]+/g, "")
            .slice(-6) || "000001";
        const created = await createCustomer({
          code: `CUS-${customerSlug}-${soSuffix}`,
          name: form.customer_name.trim(),
          email: form.email || undefined,
          address: shipping.recipient_address || undefined,
          is_active: true,
        });
        customerId = created.id;
      }
      const validLines = lines.filter((l) => l.product);
      const userId = pb.authStore.model?.id as string;

      const term = paymentTerms.find((t) => t.id === form.payment_term);
      const isCash =
        !form.payment_term ||
        (term?.days ?? 0) === 0 ||
        !form.due_date ||
        form.due_date.slice(0, 10) === form.transaction_date.slice(0, 10);
      const txNo = form.transaction_no.trim();
      if (!txNo) {
        setError("Nomor SO belum tersedia, coba simpan ulang.");
        return;
      }
      if (!isEdit) {
        await assertDocNoAvailable(
          BIZ_DOC_NUMBER_CONFIG.so,
          txNo,
          isSoEdit ? (editSoId ?? undefined) : undefined,
        );
      }
      const textNotes = [form.message, form.memo].filter(Boolean).join("\n");
      const notesWithRef = prependReferenceToNotes(textNotes, form.ref_no);
      const notesWithShipping = buildNotesWithShipping(notesWithRef, shipping);
      const notes = appendBankTransferToNotes(notesWithShipping, {
        ...transferInfo,
        enabled: transferInfo.enabled && !!(transferInfo.bank_name && transferInfo.account_number),
      });

      const stockLines = validLines.map((l) => ({
        product: l.product,
        productName: products.find((p) => p.id === l.product)?.name,
        qty: l.qty,
      }));

      if (!isEdit) {
        const stockMsg = await validateStockForSale(form.warehouse, stockLines);
        if (stockMsg) {
          setError(stockMsg);
          return;
        }
      }

      if (isSoEdit && editSoId) {
        const linked = await fetchInvoiceBySalesOrder(editSoId);
        if (linked) {
          setError(`SO sudah punya invoice ${linked.invoice_no}. Edit lewat halaman invoice.`);
          return;
        }

        const updatedSo = await updateSalesOrder(editSoId, {
          customer: customerId,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          due_date: form.due_date || undefined,
          payment_method: form.payment_method,
          notes,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
          status: "draft",
        });

        await Promise.all(editLineIds.map((lid) => deleteSalesOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createSalesOrderLine({
              sales_order: editSoId,
              product: l.product,
              sku_snapshot: products.find((p) => p.id === l.product)?.sku ?? "",
              name_snapshot: products.find((p) => p.id === l.product)?.name ?? l.description,
              qty: l.qty,
              unit_price: l.unit_price,
              discount_percent: l.discount_percent,
              discount_amount: l.qty * l.unit_price * (l.discount_percent / 100),
              tax_percent: 0,
              line_total: calcLineTotal(l),
            }),
          ),
        );
        if (form.send_to_warehouse && !updatedSo.send_to_warehouse_at) {
          await sendSalesOrderToWarehouse(editSoId, userId);
        }

        router.push(`/bisnis/penjualan/${editSoId}`);
        return;
      }

      if (isEdit && editInvoiceId && editSoId) {
        await updateSalesOrder(editSoId, {
          customer: customerId,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          due_date: form.due_date || undefined,
          payment_method: form.payment_method,
          notes,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
        });
        await Promise.all(editLineIds.map((lid) => deleteSalesOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createSalesOrderLine({
              sales_order: editSoId,
              product: l.product,
              sku_snapshot: products.find((p) => p.id === l.product)?.sku ?? "",
              name_snapshot: products.find((p) => p.id === l.product)?.name ?? l.description,
              qty: l.qty,
              unit_price: l.unit_price,
              discount_percent: l.discount_percent,
              discount_amount: l.qty * l.unit_price * (l.discount_percent / 100),
              tax_percent: 0,
              line_total: calcLineTotal(l),
            }),
          ),
        );
        await updateInvoice(editInvoiceId, {
          customer: customerId,
          issue_date: form.transaction_date,
          due_date: isCash ? form.transaction_date : form.due_date || form.transaction_date,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
          paid_amount: isCash ? grandTotal : undefined,
          remaining: isCash ? 0 : undefined,
          status: isCash ? "paid" : undefined,
          is_cash: isCash,
          notes,
        });

        if (form.warehouse && validLines.length > 0) {
          await voidStockMovementsByReference(
            {
              referenceId: editSoId,
              referenceType: "SALES_ORDER",
              referenceNo: txNo,
            },
            `Edit penjualan ${txNo}`,
          );
          const stockMsg = await validateStockForSale(form.warehouse, stockLines);
          if (stockMsg) {
            setError(stockMsg);
            return;
          }
          await createAutoStockMovement({
            type: "SALE",
            warehouse: form.warehouse,
            reference_type: "SALES_ORDER",
            reference_id: editSoId,
            reference_no: txNo,
            lines: validLines.map((l) => ({ product: l.product, qty: l.qty })),
          });
        }

        router.push(`/bisnis/penjualan/${editInvoiceId}`);
        return;
      }

      const so = await createSalesOrder({
        order_no: txNo,
        customer: customerId,
        warehouse: form.warehouse,
        order_date: form.transaction_date,
        due_date: form.due_date || undefined,
        payment_method: form.payment_method,
        notes,
        created_by: userId,
        status: "draft",
        subtotal,
        discount_amount: extraDiscount,
        tax_amount: totalTax,
        materai_amount: materai,
        total: grandTotal,
      });

      await Promise.all(
        validLines.map((l) =>
          createSalesOrderLine({
            sales_order: so.id,
            product: l.product,
            sku_snapshot: products.find((p) => p.id === l.product)?.sku ?? "",
            name_snapshot: products.find((p) => p.id === l.product)?.name ?? l.description,
            qty: l.qty,
            unit_price: l.unit_price,
            discount_percent: l.discount_percent,
            discount_amount: l.qty * l.unit_price * (l.discount_percent / 100),
            tax_percent: 0,
            line_total: calcLineTotal(l),
          }),
        ),
      );

      if (form.send_to_warehouse) {
        await sendSalesOrderToWarehouse(so.id, userId);
      }

      router.push(`/bisnis/penjualan/${so.id}`);
    } catch (e: unknown) {
      const detail =
        e && typeof e === "object" && "response" in e
          ? JSON.stringify((e as Record<string, unknown>).response)
          : e instanceof Error ? e.message : "Gagal menyimpan";
      setError(String(detail));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen">
      {/* Breadcrumb + Type Selector */}
      <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Link href="/bisnis/penjualan" className="mb-1 inline-flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-700">
            <ArrowLeft className="h-3.5 w-3.5" /> Penjualan
          </Link>
          <h1 className="text-xl font-bold text-slate-900">
            {isEdit ? "Edit Penjualan" : isSoEdit ? "Edit SO" : "Buat Penjualan"}
          </h1>
          {!isEdit && !isSoEdit && (
            <p className="mt-2 text-xs text-amber-800">
              Simpan sebagai <strong>Sales Order</strong> saja. Invoice (INV) dibuat manual dari detail SO setelah
              siap — stok keluar saat invoice dibuat (atau setelah proses gudang jika lewat WMS).
            </p>
          )}
          <label className="mt-2 inline-flex items-center gap-2 text-xs text-slate-700">
            <input
              type="checkbox"
              checked={form.send_to_warehouse}
              onChange={(e) => setForm((f) => ({ ...f, send_to_warehouse: e.target.checked }))}
              className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
            />
            Lewat gudang (WMS) — pengeluaran: kirim ke antrean Picking (gudang sumber = gudang di SO)
          </label>
        </div>
        <div className="text-right">
          <span className="text-sm text-slate-500">Total</span>
          <div className="text-xl font-bold text-slate-900">{fmt(grandTotal)}</div>
        </div>
      </div>

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 whitespace-pre-line">
          {error}
        </div>
      )}

      {/* Form Card */}
      <div className="rounded-xl border border-slate-200 bg-white shadow-sm">
        {/* Header Fields */}
        <div className="border-b border-slate-100 px-6 py-5">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Pelanggan <span className="text-red-500">*</span></label>
              <select data-nav value={form.customer} onChange={(e) => selectCustomer(e.target.value)} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih pelanggan</option>
                {customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
              {!form.customer && (
                <input
                  type="text"
                  data-nav
                  value={form.customer_name}
                  onChange={(e) => setForm((f) => ({ ...f, customer_name: e.target.value }))}
                  onKeyDown={onEnterFocusNext}
                  placeholder="Atau ketik nama pelanggan baru"
                  className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
                />
              )}
            </div>
            <div>
              <div className="mb-1 flex items-center justify-between gap-2">
                <label className="text-sm font-medium text-slate-700">Email</label>
                <ShippingInfoToggle shipping={shipping} onChange={setShipping} />
              </div>
              <input type="email" data-nav value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} onKeyDown={onEnterFocusNext} placeholder="Enter email"
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Tgl. transaksi</label>
              <input type="date" data-nav value={form.transaction_date} onChange={(e) => setForm((f) => ({ ...f, transaction_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">No. SO</label>
              <input type="text" data-nav value={form.transaction_no} onChange={(e) => setForm((f) => ({ ...f, transaction_no: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-sm font-mono text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
              <p className="mt-1 text-xs text-slate-500">{docNumberFormatHint("SO")}</p>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">No. referensi</label>
              <input
                type="text"
                data-nav
                value={form.ref_no}
                onChange={(e) => setForm((f) => ({ ...f, ref_no: e.target.value }))}
                onKeyDown={onEnterFocusNext}
                placeholder="No. pesanan MP, PO pelanggan, dll."
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100"
              />
            </div>
          </div>
          {shipping.enabled && (
            <div className="mt-4">
              <ShippingInfoSection shipping={shipping} onChange={setShipping} showToggle={false} />
            </div>
          )}
          <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Term Pembayaran</label>
              <select data-nav value={form.payment_term} onKeyDown={onEnterFocusNext} onChange={(e) => {
                const termId = e.target.value;
                const term = paymentTerms.find((t) => t.id === termId);
                if (term) {
                  const dd = new Date(form.transaction_date || Date.now());
                  dd.setDate(dd.getDate() + term.days);
                  setForm((f) => ({ ...f, payment_term: termId, due_date: dd.toISOString().slice(0, 10) }));
                } else {
                  setForm((f) => ({ ...f, payment_term: "" }));
                }
              }}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih term</option>
                {paymentTerms.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Tgl. jatuh tempo</label>
              <input type="date" data-nav value={form.due_date} onChange={(e) => setForm((f) => ({ ...f, due_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Metode Pembayaran</label>
              <select data-nav value={form.payment_method} onChange={(e) => setForm((f) => ({ ...f, payment_method: e.target.value }))} onKeyDown={onEnterFocusNext}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">{paymentMethods.length === 0 ? "— Belum ada metode (buat di Setting)" : "Pilih metode"}</option>
                {paymentMethods.map((m) => <option key={m.id} value={m.code || m.name}>{m.name}</option>)}
              </select>
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Toko <span className="text-red-500">*</span></label>
              <select data-nav value={form.store} onKeyDown={onEnterFocusNext} onChange={(e) => {
                const storeId = e.target.value;
                const selectedStore = stores.find((s) => s.id === storeId);
                setForm((f) => ({ ...f, store: storeId, warehouse: selectedStore?.default_warehouse || "" }));
              }}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100">
                <option value="">Pilih toko</option>
                {stores.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              {form.store && (
                <p className="mt-1 text-xs text-slate-400">
                  Gudang:{" "}
                  <span className="font-medium text-slate-600">
                    {stores.find((s) => s.id === form.store)?.expand?.default_warehouse?.name || "—"}
                  </span>
                  {form.warehouse && (
                    <>
                      <span className="ml-2 text-slate-500">
                        {stockLoading ? "· memuat stok…" : "· saldo inv_stock_balances (sama Stok Global)"}
                      </span>
                      <Link
                        href={`/gudang/stok?warehouse=${encodeURIComponent(form.warehouse)}`}
                        className="ml-2 font-medium text-indigo-600 hover:underline"
                      >
                        Lihat stok gudang →
                      </Link>
                    </>
                  )}
                </p>
              )}
            </div>
          </div>
          <div className="mt-3 rounded-lg border border-slate-100 bg-slate-50/70 px-3 py-2">
            <label className="flex cursor-pointer items-center gap-2 text-sm text-slate-700">
              <input
                type="checkbox"
                checked={transferInfo.enabled}
                onChange={(e) => setTransferInfo((x) => ({ ...x, enabled: e.target.checked }))}
                disabled={isCashMethod}
                className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
              />
              Tampilkan rekening transfer di catatan/cetak invoice
            </label>
            <p className="mt-1 text-xs text-slate-500">
              Sumber data dari master Toko.
            </p>
            {isCashMethod && (
              <p className="mt-1 text-xs font-medium text-amber-700">
                Metode pembayaran cash/tunai: rekening transfer otomatis disembunyikan.
              </p>
            )}
            {transferInfo.enabled && (
              <div className="mt-2 rounded border border-slate-200 bg-white px-2 py-2 text-xs text-slate-700">
                {transferInfo.bank_name || transferInfo.account_number ? (
                  <>
                    <p><span className="text-slate-500">Bank:</span> {transferInfo.bank_name || "—"}</p>
                    <p><span className="text-slate-500">No. Rek:</span> {transferInfo.account_number || "—"}</p>
                    <p><span className="text-slate-500">a.n.:</span> {transferInfo.account_name || "—"}</p>
                  </>
                ) : (
                  <p className="text-amber-700">
                    Data rekening bank di master Toko masih kosong.
                  </p>
                )}
              </div>
            )}
          </div>
          <div className="mt-3 flex items-center justify-end">
            <label className="flex items-center gap-2 text-sm text-slate-600 cursor-pointer">
              <input type="checkbox" checked={form.include_tax} onChange={(e) => setForm((f) => ({ ...f, include_tax: e.target.checked }))}
                className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500" />
              Harga termasuk pajak
            </label>
          </div>
        </div>

        {/* Product Lines Table */}
        <div className="overflow-x-auto">
          <table className="w-full table-fixed text-sm">
            <colgroup>
              <col className="w-[34%]" />
              <col className="w-[12%]" />
              <col className="w-[8%]" />
              <col className="w-[6%]" />
              <col className="w-[14%]" />
              <col className="w-[8%]" />
              <col className="w-[16%]" />
              <col className="w-[2%]" />
            </colgroup>
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-left">
                <th className="px-3 py-3 text-xs font-semibold text-slate-600">Produk</th>
                <th className="px-2 py-3 text-xs font-semibold text-slate-600">Catatan</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Kuantitas</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Unit</th>
                <th className="px-2 py-3 text-right text-xs font-semibold text-slate-600">Harga satuan</th>
                <th className="px-2 py-3 text-center text-xs font-semibold text-slate-600">Diskon</th>
                <th className="px-2 py-3 text-right text-xs font-semibold text-slate-600">Jumlah</th>
                <th className="px-1 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {lines.map((line, idx) => (
                <tr key={idx} className="group align-top">
                  <td className="px-3 py-2">
                    <select
                      data-nav
                      value={line.product}
                      onChange={(e) => updateLine(idx, "product", e.target.value)}
                      onKeyDown={onEnterFocusNext}
                      title={
                        line.product
                          ? (() => {
                              const p = products.find((x) => x.id === line.product);
                              if (!p) return undefined;
                              const st = getWarehouseStockQty(stockMap, p.id);
                              return `${p.name} · stok ${fmtNum(st)}`;
                            })()
                          : undefined
                      }
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none"
                    >
                      <option value="">Pilih produk</option>
                      {products.map((p) => {
                        const st = getWarehouseStockQty(stockMap, p.id);
                        return (
                          <option key={p.id} value={p.id}>
                            {p.name} · stok {fmtNum(st)}
                          </option>
                        );
                      })}
                    </select>
                  </td>
                  <td className="px-2 py-2">
                    <input type="text" data-nav value={line.description} onChange={(e) => updateLine(idx, "description", e.target.value)} onKeyDown={onEnterFocusNext}
                      placeholder="Catatan" className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none" />
                  </td>
                  <td className="px-2 py-2">
                    <NumSpinnerInput
                      data-nav
                      value={line.qty}
                      min={1}
                      step={1}
                      onChange={(v) => updateLine(idx, "qty", v)}
                      inputClassName="w-full min-w-0 text-center text-sm"
                    />
                  </td>
                  <td className="px-2 py-2">
                    <input type="text" data-nav value={line.unit} onChange={(e) => updateLine(idx, "unit", e.target.value)} onKeyDown={onEnterFocusNext}
                      className="w-full min-w-0 rounded border border-slate-200 px-1.5 py-1.5 text-center text-sm text-slate-700 focus:border-indigo-400 focus:outline-none" />
                  </td>
                  <td className="px-2 py-2">
                    <input
                      type="text"
                      data-nav
                      inputMode="numeric"
                      value={line.unit_price ? fmtNum(line.unit_price) : ""}
                      onChange={(e) => updateLine(idx, "unit_price", Math.max(0, parseNum(e.target.value)))}
                      onKeyDown={onEnterFocusNext}
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-right text-sm text-slate-700 focus:border-indigo-400 focus:outline-none"
                    />
                  </td>
                  <td className="px-2 py-2">
                    <NumSpinnerInput
                      data-nav
                      value={line.discount_percent}
                      min={0}
                      max={100}
                      step={1}
                      suffix="%"
                      onChange={(v) => updateLine(idx, "discount_percent", v)}
                      inputClassName="w-full min-w-0 text-center text-sm"
                    />
                  </td>
                  <td className="px-2 py-2 text-right text-sm font-medium text-slate-900 whitespace-nowrap">
                    {fmt(calcLineTotal(line))}
                  </td>
                  <td className="px-2 py-2">
                    <button onClick={() => removeLine(idx)} className="rounded p-1 text-slate-300 opacity-0 transition hover:text-red-500 group-hover:opacity-100">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="border-t border-slate-100 px-4 py-3">
          <button type="button" data-nav-add-line onClick={() => {
            addLine();
            setTimeout(() => {
              document.querySelectorAll<HTMLElement>("tbody tr:last-child select[data-nav]")[0]?.focus();
            }, 50);
          }} className="inline-flex items-center gap-1 text-sm font-medium text-indigo-600 hover:text-indigo-700">
            <Plus className="h-4 w-4" /> Tambah baris
          </button>
        </div>

        {/* Bottom section: Notes + Summary */}
        <div className="grid grid-cols-1 gap-0 border-t border-slate-200 lg:grid-cols-2">
          {/* Left - Notes */}
          <div className="border-b border-slate-200 p-6 lg:border-b-0 lg:border-r">
            <div className="space-y-4">
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">Pesan</label>
                <textarea data-nav rows={3} value={form.message} onChange={(e) => setForm((f) => ({ ...f, message: e.target.value }))} onKeyDown={onEnterFocusNext} placeholder="Pesan"
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">Memo</label>
                <textarea data-nav rows={3} value={form.memo} onChange={(e) => setForm((f) => ({ ...f, memo: e.target.value }))} onKeyDown={onEnterFocusNext} placeholder="Memo"
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-100" />
              </div>
            </div>
          </div>

          {/* Right - Summary */}
          <div className="p-6">
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-600">Subtotal</span>
                <span className="font-medium text-slate-900">{fmt(subtotal)}</span>
              </div>
              {lineDiscount > 0 && (
                <div className="flex justify-between text-slate-500">
                  <span>Diskon per baris</span>
                  <span>{fmt(lineDiscount)}</span>
                </div>
              )}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-slate-600">Diskon</span>
                  <select data-nav value={discountType} onChange={(e) => setDiscountType(e.target.value as "percent" | "amount")} onKeyDown={onEnterFocusNext}
                    className="rounded border border-slate-200 px-2 py-0.5 text-xs text-slate-600">
                    <option value="percent">%</option>
                    <option value="amount">Rp</option>
                  </select>
                  <input data-nav type="text" inputMode="numeric" value={discountValue ? fmtNum(discountValue) : ""}
                    onChange={(e) => setDiscountValue(Math.max(0, parseNum(e.target.value)))} onKeyDown={onEnterFocusNext}
                    className="w-24 rounded border border-slate-200 px-2 py-0.5 text-right text-xs text-slate-700" />
                </div>
                <span className="text-slate-500">{fmt(extraDiscount)}</span>
              </div>
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-slate-600">PPN / Pajak</span>
                  <select data-nav value={form.tax_percent}
                    onChange={(e) => setForm((f) => ({ ...f, tax_percent: Number(e.target.value) }))}
                    onKeyDown={onEnterFocusNext}
                    className="rounded border border-slate-200 px-2 py-0.5 text-xs text-slate-600">
                    <option value={0}>Tanpa Pajak</option>
                    {taxRates.map((t) => <option key={t.id} value={t.rate}>{t.name}</option>)}
                  </select>
                  {form.include_tax && (
                    <span className="text-[11px] font-medium text-indigo-600">included</span>
                  )}
                </div>
                <span className="text-slate-500">{fmt(totalTax)}</span>
              </div>
              <div className="flex items-center justify-between gap-2">
                <span className="text-slate-600">Biaya Materai</span>
                <div className="flex items-center gap-2">
                  <input data-nav type="text" inputMode="numeric"
                    value={form.materai_amount ? fmtNum(form.materai_amount) : ""}
                    onChange={(e) => setForm((f) => ({ ...f, materai_amount: Math.max(0, parseNum(e.target.value)) }))}
                    onKeyDown={onEnterFocusNext}
                    placeholder="0"
                    className="w-32 rounded border border-slate-200 px-2 py-0.5 text-right text-xs text-slate-700" />
                  {materai > 0 && <span className="text-slate-500">{fmt(materai)}</span>}
                </div>
              </div>
              {shippingCost > 0 && (
                <div className="flex justify-between">
                  <span className="text-slate-600">Ongkir</span>
                  <span className="text-slate-500">{fmt(shippingCost)}</span>
                </div>
              )}
              <div className="flex justify-between border-t border-slate-200 pt-3">
                <span className="text-base font-bold text-slate-900">Total</span>
                <span className="text-base font-bold text-slate-900">{fmt(grandTotal)}</span>
              </div>
              <div className="flex justify-between border-t border-slate-200 pt-3">
                <span className="font-semibold text-slate-700">Sisa tagihan</span>
                <span className="text-lg font-bold text-slate-900">{fmt(grandTotal)}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-3 border-t border-slate-200 px-6 py-4">
          <Link href="/bisnis/penjualan" className="rounded-lg border border-slate-300 px-5 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50">
            Batal
          </Link>
          <button type="button" data-nav onClick={handleSubmit} disabled={submitting}
            className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-indigo-700 disabled:opacity-50">
            {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
            {isEdit || isSoEdit ? "Simpan Perubahan" : "Simpan SO"}
          </button>
        </div>
      </div>
    </div>
  );
}
