"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, Plus, Trash2, Loader2, RotateCcw, Printer, Pencil, CreditCard, X, FileText, Ban } from "lucide-react";
import { pb } from "@/lib/pocketbase";
import { INV_COLLECTIONS } from "@/lib/inventory/types";
import {
  createPurchaseOrder,
  createPurchaseOrderLine,
  updatePurchaseOrder,
  updatePurchaseBill,
  deletePurchaseOrderLine,
  fetchPurchaseBill,
  fetchPurchaseOrder,
  fetchPurchaseOrderLines,
  fetchAllSuppliers,
  replaceAutoStockMovement,
  voidStockMovementsByReference,
  fetchStores,
  fetchTaxRates,
  fetchPaymentTerms,
  fetchPaymentMethods,
  fetchPurchaseBillByPurchaseOrder,
  canEditPurchaseOrder,
  sendPurchaseOrderToWarehouse,
  createBillFromPurchaseOrder,
  cancelPurchaseOrderWithoutBill,
  createPurchaseReturFromOrderApi,
  canCreateBillFromPurchaseOrder,
  canSendPurchaseOrderToWarehouse,
  billBlockedReason,
} from "@/lib/bisnis/client";
import { canEditPurchaseBill } from "@/lib/bisnis/purchase-status";
import { updateProductBuyPrice } from "@/lib/inventory/client";
import { fetchCompanyProfiles } from "@/lib/bisnis/company-client";
import type {
  Supplier,
  Store,
  TaxRate,
  PaymentTerm,
  PaymentMethodSetting,
  CompanyProfile,
  PurchaseBill,
  PurchaseOrder,
  CashAccount,
} from "@/lib/bisnis/types";
import Link from "next/link";
import { NumSpinnerInput, fmtNum, parseNum } from "@/components/bisnis/NumSpinnerInput";
import { ShippingInfoSection, ShippingInfoToggle } from "@/components/bisnis/ShippingInfoSection";
import { fetchCouriersCatalogCached, prefetchCouriers } from "@/lib/bisnis/couriers";
import { useLgUp } from "@/lib/ui/use-media-query";
import { onEnterFocusNext, onLineFieldEnter, onLineSpinnerEnter } from "@/lib/bisnis/form-nav";
import { PurchaseProcessTimeline } from "@/components/bisnis/PurchaseProcessTimeline";
import { PurchaseQcExceptionPanel } from "@/components/bisnis/PurchaseQcExceptionPanel";
import { applyBillPayment } from "@/lib/bisnis/bill-payment";
import { fetchCashAccounts } from "@/lib/bisnis/cash-client";
import { pickPrimaryCashAccountId } from "@/lib/bisnis/entity-modules";
import { findPaymentMethod } from "@/lib/bisnis/payment-method-value";
import {
  buildNotesWithShipping,
  emptyShippingInfo,
  enrichShippingFromCatalog,
  isShippingActive,
  loadShippingForForm,
  normalizeShippingForSave,
  parseNotesWithShipping,
  type ShippingInfo,
} from "@/lib/bisnis/shipping-notes";
import {
  assertDocNoAvailable,
  BIZ_DOC_NUMBER_CONFIG,
  docNumberFormatHint,
  isAutoGeneratedDocNo,
  nextDocNoFor,
} from "@/lib/bisnis/doc-number";
import { emitBusinessEvent } from "@/lib/tenant/activity-events";
import { parseReferenceFromNotes } from "@/lib/bisnis/reference-notes";
import { getErrorMessage } from "@/lib/errors";
import { purchaseCreateUrl } from "@/lib/bisnis/module-routes";
import { lookupPurchaseDocByNumber, type PurchaseDocLookup } from "@/lib/bisnis/doc-lookup";
import { buildPurchasePostSavePayload } from "@/lib/bisnis/post-save-print";
import { openBizDocumentPrint } from "@/lib/bisnis/doc-print";
import { canCreatePurchaseRetur } from "@/lib/bisnis/purchase-retur-guards";
import { DocOpenChoiceModal } from "@/components/bisnis/DocOpenChoiceModal";
import { fetchWarehouseStockMap, getWarehouseStockQty } from "@/lib/bisnis/warehouse-stock";
import { useWorkContext } from "@/components/WorkContextProvider";
import { getPrimaryReceivingWarehouse } from "@/lib/bisnis/entity-modules";
import { useLocale } from "@/components/LocaleProvider";
function mergeLegacyReferenceNotes(reference: string, body: string): string {
  if (!reference) return body;
  return body ? `${reference}\n${body}` : reference;
}

function inferPaymentTermId(
  terms: PaymentTerm[],
  orderDate: string,
  dueDate?: string,
): string {
  if (!terms.length || !orderDate) return "";
  const order = orderDate.slice(0, 10);
  const due = dueDate?.slice(0, 10);
  if (!due || due === order) {
    return terms.find((t) => t.days === 0)?.id ?? "";
  }
  const diffDays = Math.round(
    (new Date(due).getTime() - new Date(order).getTime()) / 86400000,
  );
  const exact = terms.find((t) => t.days === diffDays);
  if (exact) return exact.id;
  const credit = terms.filter((t) => t.days > 0);
  if (!credit.length) return "";
  const closest = credit.reduce((best, t) =>
    Math.abs(t.days - diffDays) < Math.abs(best.days - diffDays) ? t : best,
  );
  return closest.id;
}

const fmt = (v: number) =>
  new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(v);

type Product = { id: string; sku: string; name: string; buy_price?: number; unit?: string };

type LineItem = {
  product: string;
  description: string;
  qty: number;
  unit: string;
  unit_cost: number;
  discount_percent: number;
};

const emptyLine = (): LineItem => ({
  product: "", description: "", qty: 1, unit: "pcs", unit_cost: 0, discount_percent: 0,
});

type PurchaseSaveTarget =
  | { kind: "bill"; billId: string; poId: string }
  | { kind: "po"; poId: string };

const pickAddress = (supplier?: Supplier) =>
  [supplier?.address, supplier?.city].filter(Boolean).join(", ");

export default function BuatPembelianPage() {
  const { t } = useLocale();
  const { context: workCtx, companies, setContext } = useWorkContext();
  const [selectedCompanyId, setSelectedCompanyId] = useState("");
  const activeCompanyId = selectedCompanyId || workCtx?.companyId || "";
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("edit");
  const poEditId = searchParams.get("po");
  const createType = searchParams.get("type") === "bill" ? "bill" : "po";
  const isEdit = !!editId;
  const isPoEdit = !!poEditId && !editId;
  const isBillCreate = !isEdit && !isPoEdit && createType === "bill";
  const usesBillNo = isBillCreate || isEdit;

  const [editBillId, setEditBillId] = useState<string | null>(null);
  const [editPoId, setEditPoId] = useState<string | null>(null);
  const [editLineIds, setEditLineIds] = useState<string[]>([]);
  const [loadingEdit, setLoadingEdit] = useState(!!editId || !!poEditId);

  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [companyProfiles, setCompanyProfiles] = useState<CompanyProfile[]>([]);
  const [stores, setStores] = useState<Store[]>([]);
  const [receivingWarehouse, setReceivingWarehouse] = useState<{
    id: string;
    name: string;
    code: string;
  } | null>(null);
  const [products, setProducts] = useState<Product[]>([]);
  const [taxRates, setTaxRates] = useState<TaxRate[]>([]);
  const [paymentTerms, setPaymentTerms] = useState<PaymentTerm[]>([]);
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethodSetting[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [docChoice, setDocChoice] = useState<PurchaseDocLookup | null>(null);
  const [docChoiceLoading, setDocChoiceLoading] = useState(false);
  const [editCanRetur, setEditCanRetur] = useState(false);

  const [form, setForm] = useState({
    supplier: "",
    email: "",
    transaction_date: new Date().toISOString().slice(0, 10),
    due_date: "",
    transaction_no: "",
    store: "",
    warehouse: "",
    payment_term: "",
    payment_method: "",
    memo: "",
    include_tax: false,
    tax_percent: 0,
    materai_amount: 0,
    send_to_warehouse: false,
  });

  const [lines, setLines] = useState<LineItem[]>([emptyLine()]);
  const [discountType, setDiscountType] = useState<"percent" | "amount">("percent");
  const [discountValue, setDiscountValue] = useState(0);
  const [stockMap, setStockMap] = useState<Record<string, number>>({});
  const [stockLoading, setStockLoading] = useState(false);
  const [shipping, setShipping] = useState<ShippingInfo>(emptyShippingInfo);
  const [linkedBill, setLinkedBill] = useState<PurchaseBill | null>(null);
  const [creatingBill, setCreatingBill] = useState(false);
  const [cancellingPo, setCancellingPo] = useState(false);
  const [sendingWarehouse, setSendingWarehouse] = useState(false);
  const [docViewLocked, setDocViewLocked] = useState(false);
  const [editReloadToken, setEditReloadToken] = useState(0);
  const [timelinePo, setTimelinePo] = useState<PurchaseOrder | null>(null);
  const [editBill, setEditBill] = useState<PurchaseBill | null>(null);
  const [showPayModal, setShowPayModal] = useState(false);
  const [paySubmitting, setPaySubmitting] = useState(false);
  const [cashAccounts, setCashAccounts] = useState<CashAccount[]>([]);
  const [payForm, setPayForm] = useState({
    amount: 0,
    payment_method: "",
    cash_account: "",
    payment_date: new Date().toISOString().slice(0, 10),
    notes: "",
  });

  const fieldsLocked = (isEdit || isPoEdit) && docViewLocked;
  const lgUp = useLgUp();
  const showProductStock = !isEdit && !isPoEdit;

  useEffect(() => {
    setDocViewLocked(isEdit || isPoEdit);
  }, [editId, poEditId, isEdit, isPoEdit]);

  useEffect(() => {
    prefetchCouriers(true);
  }, []);

  useEffect(() => {
    if (isShippingActive(shipping)) prefetchCouriers(true);
  }, [shipping]);

  useEffect(() => {
    if (shipping.courier.trim() || !shipping.shipping_service.trim()) return;
    let cancelled = false;
    void fetchCouriersCatalogCached(true).then(() => {
      if (cancelled) return;
      setShipping((prev) => {
        const enriched = enrichShippingFromCatalog(prev);
        return enriched.courier === prev.courier ? prev : enriched;
      });
    });
    return () => {
      cancelled = true;
    };
  }, [shipping.courier, shipping.shipping_service, editPoId, poEditId, editId, editReloadToken]);

  const entityOptions = (() => {
    if (companies.length) {
      return companies.map((c) => ({
        id: c.id,
        label: c.code ? `${c.code} — ${c.name}` : c.name,
      }));
    }
    if (companyProfiles.length) {
      return companyProfiles.map((c) => ({
        id: c.id,
        label: c.code ? `${c.code} — ${c.company_name}` : c.company_name,
      }));
    }
    if (workCtx?.companyId && workCtx.companyName) {
      return [{ id: workCtx.companyId, label: workCtx.companyName }];
    }
    return [];
  })();

  useEffect(() => {
    if (entityOptions.length === 1 && !selectedCompanyId && !isEdit && !isPoEdit) {
      void handleCompanyChange(entityOptions[0].id);
    }
  }, [entityOptions, selectedCompanyId, isEdit, isPoEdit]);

  useEffect(() => {
    if (workCtx?.companyId && !selectedCompanyId) {
      setSelectedCompanyId(workCtx.companyId);
    }
  }, [workCtx?.companyId, selectedCompanyId]);

  const handleCompanyChange = async (companyId: string) => {
    setSelectedCompanyId(companyId);
    if (companyId) void setContext({ companyId });
    const primaryWh = companyId ? await getPrimaryReceivingWarehouse(companyId) : null;
    setReceivingWarehouse(primaryWh);
    const st = companyId ? await fetchStores(false, companyId) : [];
    setStores(st);
    setForm((f) => ({
      ...f,
      warehouse: primaryWh?.id ?? "",
      store: st.find((x) => x.default_warehouse === primaryWh?.id)?.id ?? st[0]?.id ?? "",
    }));
  };

  useEffect(() => {
    if (!form.warehouse) {
      setStockMap({});
      return;
    }
    let cancelled = false;
    setStockLoading(true);
    fetchWarehouseStockMap(form.warehouse)
      .then((map) => {
        if (!cancelled) setStockMap(map);
      })
      .catch(() => {
        if (!cancelled) setStockMap({});
      })
      .finally(() => {
        if (!cancelled) setStockLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [form.warehouse]);

  useEffect(() => {
    if (isEdit || isPoEdit) return;
    const kind = isBillCreate ? "bill" : "po";
    const cfg = BIZ_DOC_NUMBER_CONFIG[kind];
    nextDocNoFor(kind, { periodDate: form.transaction_date })
      .then((no) => {
        setForm((f) => {
          if (
            f.transaction_no &&
            !isAutoGeneratedDocNo(f.transaction_no, cfg.prefix, f.transaction_date)
          ) {
            return f;
          }
          return { ...f, transaction_no: no };
        });
      })
      .catch(() => {});
  }, [isEdit, isPoEdit, isBillCreate, form.transaction_date]);

  useEffect(() => {
    Promise.all([
      fetchAllSuppliers(),
      fetchCompanyProfiles(true).catch(() => [] as CompanyProfile[]),
      fetchStores(false, activeCompanyId || undefined),
      activeCompanyId ? getPrimaryReceivingWarehouse(activeCompanyId) : Promise.resolve(null),
      (async () => {
        const { fetchOperationalProductsPb } = await import("@/lib/catalog/product-query");
        return fetchOperationalProductsPb<Product>(pb, { sort: "name" });
      })(),
      fetchTaxRates().catch(() => [] as TaxRate[]),
      fetchPaymentTerms().catch(() => [] as PaymentTerm[]),
      fetchPaymentMethods().catch(() => [] as PaymentMethodSetting[]),
    ]).then(([s, co, st, primaryWh, p, tr, pt, pm]) => {
      setSuppliers(s);
      setCompanyProfiles(co);
      setStores(st);
      setReceivingWarehouse(primaryWh);
      setProducts(p);
      setTaxRates(tr);
      setPaymentTerms(pt);
      setPaymentMethods(pm);
      if (!isEdit && !isPoEdit && primaryWh) {
        const linkedStore = st.find((x) => x.default_warehouse === primaryWh.id) ?? st[0];
        setForm((f) => ({
          ...f,
          store: linkedStore?.id ?? "",
          warehouse: primaryWh.id,
        }));
      }
      const defaultTerm = pt.find((t) => t.is_default);
      if (defaultTerm) {
        const dd = new Date();
        dd.setDate(dd.getDate() + defaultTerm.days);
        setForm((f) => ({ ...f, payment_term: defaultTerm.id, due_date: dd.toISOString().slice(0, 10) }));
      }
      const defaultTax = tr.find((t) => t.is_default);
      if (defaultTax) setForm((f) => ({ ...f, tax_percent: defaultTax.rate }));
    }).catch(() => {});
  }, [activeCompanyId, workCtx?.storeId, workCtx?.warehouseId, isEdit, isPoEdit]);

  useEffect(() => {
    if (!poEditId || editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const poData = await fetchPurchaseOrder(poEditId);
        if (!canEditPurchaseOrder(poData)) {
          const linked = await fetchPurchaseBillByPurchaseOrder(poData.id);
          router.replace(linked ? `/bisnis/pembelian/${linked.id}` : `/bisnis/pembelian/${poData.id}`);
          return;
        }
        setEditPoId(poData.id);
        setTimelinePo(poData);
        setEditCanRetur(canCreatePurchaseRetur(poData));
        setLinkedBill(await fetchPurchaseBillByPurchaseOrder(poData.id).catch(() => null));
        const poLines = await fetchPurchaseOrderLines(poEditId);
        setEditLineIds(poLines.map((l) => l.id));
        await fetchCouriersCatalogCached(true).catch(() => {});
        const ship = loadShippingForForm([{ notes: poData.notes ?? "" }]);
        const { textNotes } = parseNotesWithShipping(poData.notes ?? "");
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = mergeLegacyReferenceNotes(reference, body).split("\n");
        const orderDate = poData.order_date?.slice(0, 10) ?? "";
        const dueDate = poData.expected_date?.slice(0, 10) ?? "";
        setShipping(ship);
        setForm((f) => ({
          ...f,
          supplier: poData.supplier,
          email: poData.expand?.supplier?.email ?? "",
          transaction_date: orderDate || f.transaction_date,
          due_date: dueDate,
          transaction_no: poData.po_no,
          payment_term: inferPaymentTermId(paymentTerms, orderDate, dueDate),
          materai_amount: poData.materai_amount ?? 0,
          memo: noteParts.filter(Boolean).join("\n"),
          send_to_warehouse: !!poData.send_to_warehouse_at,
        }));
        if ((poData.discount_amount ?? 0) > 0) {
          setDiscountType("amount");
          setDiscountValue(poData.discount_amount ?? 0);
        }
        if (poLines.length > 0) {
          setLines(
            poLines.map((l) => ({
              product: l.product,
              description: l.expand?.product?.name ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_cost: l.unit_cost,
              discount_percent: 0,
            })),
          );
        }
        if (poData.company) setSelectedCompanyId(poData.company);
        const wh = poData.warehouse;
        if (wh) {
          const store = stores.find((s) => s.default_warehouse === wh);
          setForm((f) => ({
            ...f,
            store: store?.id ?? f.store,
            warehouse: wh,
          }));
        }
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : t("purchase.create.errLoadPo"));
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [poEditId, editId, stores, paymentTerms, editReloadToken]);

  useEffect(() => {
    if (!editId) return;
    (async () => {
      setLoadingEdit(true);
      try {
        const bill = await fetchPurchaseBill(editId);
        if (!canEditPurchaseBill(bill)) {
          setError(t("purchase.create.errCancelled"));
          return;
        }
        setEditBillId(bill.id);
        setEditBill(bill);
        setLinkedBill(bill);
        const poId = bill.purchase_order ?? null;
        setEditPoId(poId);
        if (poId) {
          try {
            const linkedPo = await fetchPurchaseOrder(poId);
            setTimelinePo(linkedPo);
            setEditCanRetur(canCreatePurchaseRetur(linkedPo));
          } catch {
            setTimelinePo(null);
            setEditCanRetur(false);
          }
        } else {
          setTimelinePo(null);
          setEditCanRetur(false);
        }
        const poLines = poId ? await fetchPurchaseOrderLines(poId) : [];
        setEditLineIds(poLines.map((l) => l.id));

        const rawNotesBill = bill.notes ?? "";
        const rawNotesPo = bill.expand?.purchase_order?.notes ?? "";
        await fetchCouriersCatalogCached(true).catch(() => {});
        const ship = loadShippingForForm([
          { notes: rawNotesPo },
          { notes: rawNotesBill },
        ]);
        const rawNotes = rawNotesBill || rawNotesPo;
        const { textNotes } = parseNotesWithShipping(rawNotes);
        const { reference, body } = parseReferenceFromNotes(textNotes);
        const noteParts = mergeLegacyReferenceNotes(reference, body).split("\n");
        const orderDate = bill.bill_date?.slice(0, 10) ?? "";
        const dueDate = bill.due_date?.slice(0, 10) ?? "";
        setShipping(ship);
        setForm((f) => ({
          ...f,
          supplier: bill.supplier,
          email: bill.expand?.supplier?.email ?? "",
          transaction_date: orderDate || f.transaction_date,
          due_date: dueDate,
          transaction_no: bill.bill_no,
          payment_term: inferPaymentTermId(paymentTerms, orderDate, dueDate),
          materai_amount: bill.materai_amount ?? 0,
          memo: noteParts.filter(Boolean).join("\n"),
          send_to_warehouse: !!bill.expand?.purchase_order?.send_to_warehouse_at,
        }));

        if ((bill.discount_amount ?? 0) > 0) {
          setDiscountType("amount");
          setDiscountValue(bill.discount_amount ?? 0);
        }

        if (bill.tax_amount > 0 && bill.subtotal > 0) {
          const rate = Math.round((bill.tax_amount / (bill.subtotal - (bill.discount_amount ?? 0))) * 10000) / 100;
          setForm((f) => ({ ...f, tax_percent: rate }));
        }

        if (poLines.length > 0) {
          setLines(
            poLines.map((l) => ({
              product: l.product,
              description: l.expand?.product?.name ?? "",
              qty: l.qty,
              unit: "pcs",
              unit_cost: l.unit_cost,
              discount_percent: 0,
            })),
          );
        }

        const wh = bill.expand?.purchase_order?.warehouse;
        if (wh) {
          const store = stores.find((s) => s.default_warehouse === wh);
          if (store) {
            setForm((f) => ({ ...f, store: store.id, warehouse: wh }));
          } else {
            setForm((f) => ({ ...f, warehouse: wh }));
          }
        }
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : t("purchase.create.errLoadEdit"));
      } finally {
        setLoadingEdit(false);
      }
    })();
  }, [editId, stores, paymentTerms, editReloadToken]);

  const selectSupplier = (id: string) => {
    const sup = suppliers.find((s) => s.id === id);
    setForm((f) => ({ ...f, supplier: id, email: sup?.email ?? "" }));
    setShipping((s) =>
      s.enabled ? { ...s, recipient_address: pickAddress(sup) || s.recipient_address } : s,
    );
  };

  const handleShippingChange = useCallback((next: ShippingInfo) => {
    if (shipping.enabled && !next.enabled) {
      setShipping(emptyShippingInfo());
      return;
    }
    setShipping(next);
  }, [shipping.enabled]);

  const updateLine = (idx: number, field: keyof LineItem, value: string | number) => {
    setLines((prev) => {
      const next = [...prev];
      if (field === "product") {
        const prod = products.find((p) => p.id === value);
        const productId = value as string;
        next[idx] = {
          ...next[idx],
          product: productId,
          unit: prod?.unit ?? "pcs",
          unit_cost: prod?.buy_price ?? next[idx].unit_cost,
          qty: productId ? 1 : next[idx].qty,
        };
      } else {
        (next[idx] as Record<string, unknown>)[field] = value;
      }
      return next;
    });
  };

  const addLine = () => setLines((prev) => [...prev, emptyLine()]);
  const removeLine = (idx: number) => setLines((prev) => (prev.length <= 1 ? prev : prev.filter((_, i) => i !== idx)));

  const calcLineTotal = (l: LineItem) => {
    const gross = l.qty * l.unit_cost;
    return gross - gross * (l.discount_percent / 100);
  };

  const subtotal = lines.reduce((s, l) => s + calcLineTotal(l), 0);
  const extraDiscount = discountType === "percent" ? subtotal * (discountValue / 100) : discountValue;
  const afterDiscount = subtotal - extraDiscount;
  const totalTax = form.include_tax
    ? (afterDiscount * form.tax_percent) / (100 + form.tax_percent || 1)
    : afterDiscount * (form.tax_percent / 100);
  const taxExclusiveSubtotal = form.include_tax ? afterDiscount - totalTax : afterDiscount;
  const showShippingPanel =
    shipping.enabled || (fieldsLocked && isShippingActive(shipping));
  const shippingCost = showShippingPanel ? Math.max(0, shipping.shipping_cost || 0) : 0;
  const materai = form.materai_amount || 0;
  const grandTotal = taxExclusiveSubtotal + totalTax + shippingCost + materai;
  const selectedStore = stores.find((s) => s.id === form.store);
  const billRemaining = editBill?.remaining ?? grandTotal;
  const canPayBill = isEdit && editBill && (editBill.remaining ?? 0) > 0.01;

  const poWorkflow = timelinePo;
  const canBillFromPo =
    isPoEdit &&
    !!editPoId &&
    !!poWorkflow &&
    !linkedBill &&
    canCreateBillFromPurchaseOrder(poWorkflow);
  const billBlockReason = poWorkflow ? billBlockedReason(poWorkflow) : null;
  const canSendWhFromPo =
    isPoEdit && !!poWorkflow && canSendPurchaseOrderToWarehouse(poWorkflow);
  const canCancelOpenPo =
    isPoEdit &&
    !!editPoId &&
    !!poWorkflow &&
    poWorkflow.status !== "cancelled" &&
    !linkedBill &&
    canEditPurchaseOrder(poWorkflow);

  const resetToNew = useCallback(() => {
    setEditBillId(null);
    setEditPoId(null);
    setEditLineIds([]);
    setEditCanRetur(false);
    setError(null);
    setLines([emptyLine()]);
    setDiscountType("percent");
    setDiscountValue(0);
    setShipping(emptyShippingInfo());
    setLinkedBill(null);
    const periodDate = new Date().toISOString().slice(0, 10);
    setForm((f) => ({
      ...f,
      supplier: "",
      email: "",
      transaction_date: periodDate,
      due_date: "",
      transaction_no: "",
      memo: "",
      materai_amount: 0,
      send_to_warehouse: false,
    }));
    router.replace(purchaseCreateUrl(createType === "bill" ? "bill" : "po"));
  }, [router, createType]);

  const handleDocNoBlur = useCallback(async () => {
    if (isEdit || isPoEdit) return;
    const q = form.transaction_no.trim();
    if (!q) return;
    try {
      const hit = await lookupPurchaseDocByNumber(q);
      if (hit) setDocChoice(hit);
    } catch {
      /* abaikan */
    }
  }, [form.transaction_no, isEdit, isPoEdit]);

  const openDocForEdit = useCallback(
    (hit: PurchaseDocLookup) => {
      setDocChoice(null);
      if (hit.mode === "bill") {
        router.replace(`/bisnis/pembelian/buat?edit=${hit.billId}`);
        return;
      }
      router.replace(`/bisnis/pembelian/buat?po=${hit.poId}`);
    },
    [router],
  );

  const startReturFromPo = useCallback(
    async (poId: string) => {
      setDocChoiceLoading(true);
      setError(null);
      try {
        const { retur } = await createPurchaseReturFromOrderApi(poId);
        router.push(`/bisnis/retur/${retur.id}`);
      } catch (e: unknown) {
        setError(getErrorMessage(e, "Gagal membuat retur pembelian"));
      } finally {
        setDocChoiceLoading(false);
        setDocChoice(null);
      }
    },
    [router],
  );

  const handleEditRetur = useCallback(async () => {
    if (!editPoId) return;
    await startReturFromPo(editPoId);
  }, [editPoId, startReturFromPo]);

  const persistDocument = async (): Promise<PurchaseSaveTarget | null> => {
    if (!form.supplier) { setError(t("purchase.create.errSupplierRequired")); return null; }
    if (!activeCompanyId) {
      setError("Pilih entitas pembeli terlebih dahulu");
      return null;
    }
    if (!form.warehouse) {
      setError("Pilih gudang penerimaan untuk entitas ini");
      return null;
    }
    if (lines.every((l) => !l.product)) { setError(t("purchase.create.errProductRequired")); return null; }

    setSubmitting(true);
    setError(null);
    try {
      const validLines = lines.filter((l) => l.product);
      const userId = pb.authStore.model?.id as string;
      const term = paymentTerms.find((t) => t.id === form.payment_term);
      const isCash =
        !form.payment_term ||
        (term?.days ?? 0) === 0 ||
        !form.due_date ||
        form.due_date.slice(0, 10) === form.transaction_date.slice(0, 10);
      const txNo = form.transaction_no.trim();
      if (!txNo) {
        setError(
          t(usesBillNo ? "purchase.create.errBillNoUnavailable" : "purchase.create.errPoNoUnavailable"),
        );
        return null;
      }
      if (!isEdit) {
        const docCfg = usesBillNo ? BIZ_DOC_NUMBER_CONFIG.bill : BIZ_DOC_NUMBER_CONFIG.po;
        await assertDocNoAvailable(
          docCfg,
          txNo,
          isPoEdit ? (editPoId ?? undefined) : undefined,
        );
      }
      const textNotes = form.memo.trim();
      await fetchCouriersCatalogCached(true).catch(() => {});
      const shippingToSave = normalizeShippingForSave(shipping);
      setShipping(shippingToSave);
      const notes = buildNotesWithShipping(textNotes, shippingToSave);

      if (isPoEdit && editPoId) {
        const linked = await fetchPurchaseBillByPurchaseOrder(editPoId);
        if (linked) {
          setError(t("purchase.create.errPoHasBill", { billNo: linked.bill_no }));
          return null;
        }

        const updatedPo = await updatePurchaseOrder(editPoId, {
          po_no: txNo,
          supplier: form.supplier,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          expected_date: form.due_date || undefined,
          status: "draft",
          notes,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
        });

        await Promise.all(editLineIds.map((lid) => deletePurchaseOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createPurchaseOrderLine({
              purchase_order: editPoId,
              product: l.product,
              qty: l.qty,
              received_qty: 0,
              unit_cost: l.unit_cost,
              line_total: calcLineTotal(l),
            }),
          ),
        );
        if (form.send_to_warehouse && !updatedPo.send_to_warehouse_at) {
          await sendPurchaseOrderToWarehouse(editPoId, userId);
        }

        return { kind: "po", poId: editPoId };
      }

      if (isEdit && editBillId && editPoId) {
        const existingBill = await fetchPurchaseBill(editBillId);
        const linkedPo = await fetchPurchaseOrder(editPoId);
        const poOrderNo = linkedPo.po_no;
        const paidKeep = isCash ? grandTotal : (existingBill.paid_amount ?? 0);

        await assertDocNoAvailable(BIZ_DOC_NUMBER_CONFIG.bill, txNo, editBillId);
        await updatePurchaseOrder(editPoId, {
          supplier: form.supplier,
          warehouse: form.warehouse,
          order_date: form.transaction_date,
          expected_date: form.due_date || undefined,
          status: "received",
          notes,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
        });

        await Promise.all(editLineIds.map((lid) => deletePurchaseOrderLine(lid)));
        await Promise.all(
          validLines.map((l) =>
            createPurchaseOrderLine({
              purchase_order: editPoId,
              product: l.product,
              qty: l.qty,
              received_qty: l.qty,
              unit_cost: l.unit_cost,
              line_total: calcLineTotal(l),
            }),
          ),
        );

        await updatePurchaseBill(editBillId, {
          bill_no: txNo,
          supplier: form.supplier,
          bill_date: form.transaction_date,
          due_date: isCash ? form.transaction_date : form.due_date || form.transaction_date,
          subtotal,
          discount_amount: extraDiscount,
          tax_amount: totalTax,
          materai_amount: materai,
          total: grandTotal,
          paid_amount: paidKeep,
          remaining: isCash ? 0 : Math.max(0, grandTotal - paidKeep),
          status: isCash ? "paid" : "unpaid",
          is_cash: isCash,
          notes,
        });

        if (form.warehouse && validLines.length > 0) {
          await replaceAutoStockMovement({
            type: "PURCHASE",
            warehouse: form.warehouse,
            reference_type: "PURCHASE_ORDER",
            reference_id: editPoId,
            reference_no: poOrderNo,
            lines: validLines.map((l) => ({ product: l.product, qty: l.qty })),
            voidNote: `Edit pembelian ${poOrderNo}`,
          });
        } else if (editPoId) {
          await voidStockMovementsByReference(
            {
              referenceId: editPoId,
              referenceType: "PURCHASE_ORDER",
              referenceNo: poOrderNo,
            },
            "Edit pembelian tanpa baris",
          );
        }

        await Promise.all(
          validLines.map((l) => updateProductBuyPrice(l.product, l.unit_cost).catch(() => {})),
        );

        return { kind: "bill", billId: editBillId, poId: editPoId };
      }

      const poNo = isBillCreate
        ? await nextDocNoFor("po", { periodDate: form.transaction_date })
        : txNo;

      const po = await createPurchaseOrder({
        po_no: poNo,
        supplier: form.supplier,
        warehouse: form.warehouse,
        order_date: form.transaction_date,
        expected_date: form.due_date || undefined,
        status: "draft",
        notes,
        created_by: userId,
        subtotal,
        discount_amount: extraDiscount,
        tax_amount: totalTax,
        materai_amount: materai,
        total: grandTotal,
      });

      await Promise.all(
        validLines.map((l) =>
          createPurchaseOrderLine({
            purchase_order: po.id,
            product: l.product,
            qty: l.qty,
            received_qty: 0,
            unit_cost: l.unit_cost,
            line_total: calcLineTotal(l),
          }),
        ),
      );

      if (form.send_to_warehouse) {
        await sendPurchaseOrderToWarehouse(po.id, userId);
      }

      void emitBusinessEvent({
        event_code: "purchase.order.created",
        module: "purchase",
        entity_type: "biz_purchase_orders",
        entity_id: po.id,
        entity_label: po.po_no,
        warehouse_id: form.warehouse,
        payload: { po_no: po.po_no },
        actor_id: userId,
      });

      if (isBillCreate) {
        const bill = await createBillFromPurchaseOrder(po.id, userId, { billNo: txNo });
        return { kind: "bill", billId: bill.id, poId: po.id };
      }

      return { kind: "po", poId: po.id };
    } catch (e: unknown) {
      setError(getErrorMessage(e, t("purchase.create.errSaveFailed")));
      return null;
    } finally {
      setSubmitting(false);
    }
  };

  const handleCreateBillFromPo = async () => {
    if (!editPoId) return;
    setCreatingBill(true);
    setError(null);
    try {
      const userId = pb.authStore.model?.id as string | undefined;
      if (!userId) {
        setError(t("purchase.detail.errRelogin"));
        return;
      }
      if (!docViewLocked) {
        const saved = await persistDocument();
        if (!saved) return;
      }
      const bill = await createBillFromPurchaseOrder(editPoId, userId);
      router.replace(`/bisnis/pembelian/buat?edit=${bill.id}`);
    } catch (e: unknown) {
      setError(getErrorMessage(e, t("purchase.detail.errCreateBill")));
    } finally {
      setCreatingBill(false);
    }
  };

  const handleSendPoToWarehouse = async () => {
    if (!editPoId) return;
    setSendingWarehouse(true);
    setError(null);
    try {
      const userId = pb.authStore.model?.id as string | undefined;
      if (!userId) {
        setError(t("purchase.detail.errRelogin"));
        return;
      }
      if (!docViewLocked) {
        const saved = await persistDocument();
        if (!saved) return;
      }
      const updated = await sendPurchaseOrderToWarehouse(editPoId, userId);
      setTimelinePo(updated);
      setForm((f) => ({ ...f, send_to_warehouse: true }));
    } catch (e: unknown) {
      setError(getErrorMessage(e, t("purchase.create.errSendWarehouse")));
    } finally {
      setSendingWarehouse(false);
    }
  };

  const handleCancelOpenPo = async () => {
    if (!editPoId) return;
    if (!window.confirm(t("purchase.create.cancelPoConfirm"))) return;
    setCancellingPo(true);
    setError(null);
    try {
      await cancelPurchaseOrderWithoutBill(editPoId);
      router.push("/bisnis/pembelian/pesanan");
    } catch (e: unknown) {
      setError(getErrorMessage(e, t("purchase.create.errCancelPo")));
    } finally {
      setCancellingPo(false);
    }
  };

  const reloadShippingFromPersist = useCallback(async (target: PurchaseSaveTarget) => {
    await fetchCouriersCatalogCached(true);
    if (target.kind === "bill") {
      const [freshBill, freshPo] = await Promise.all([
        fetchPurchaseBill(target.billId),
        fetchPurchaseOrder(target.poId),
      ]);
      setShipping(
        loadShippingForForm([
          { notes: freshPo.notes ?? "" },
          { notes: freshBill.notes ?? "" },
        ]),
      );
      setTimelinePo(freshPo);
    } else {
      const freshPo = await fetchPurchaseOrder(target.poId);
      setShipping(loadShippingForForm([{ notes: freshPo.notes ?? "" }]));
      setTimelinePo(freshPo);
    }
  }, []);

  const handleActionCancel = () => {
    if ((isEdit || isPoEdit) && !docViewLocked) {
      setDocViewLocked(true);
      setEditReloadToken((k) => k + 1);
      setError(null);
      return;
    }
    router.push("/bisnis/pembelian");
  };

  const handleViewPrint = async () => {
    try {
      if (editBillId && editPoId) {
        const payload = await buildPurchasePostSavePayload(
          { kind: "bill", billId: editBillId, poId: editPoId },
          selectedStore ?? null,
        );
        openBizDocumentPrint(payload.printData);
        return;
      }
      if (editPoId) {
        const payload = await buildPurchasePostSavePayload(
          { kind: "po", poId: editPoId },
          selectedStore ?? null,
        );
        openBizDocumentPrint(payload.printData);
      }
    } catch (e: unknown) {
      setError(getErrorMessage(e, "Gagal membuka cetak"));
    }
  };

  const reloadEditBill = useCallback(async () => {
    if (!editId) return;
    try {
      const bill = await fetchPurchaseBill(editId);
      setEditBill(bill);
    } catch {
      /* abaikan */
    }
  }, [editId]);

  const openPayModal = useCallback(async () => {
    if (!editBill) return;
    setPayForm({
      amount: editBill.remaining,
      payment_method: form.payment_method || "",
      cash_account: "",
      payment_date: new Date().toISOString().slice(0, 10),
      notes: "",
    });
    try {
      const accounts = await fetchCashAccounts(true, activeCompanyId || workCtx?.companyId);
      setCashAccounts(accounts);
      setPayForm((f) => ({
        ...f,
        cash_account: pickPrimaryCashAccountId(accounts),
      }));
    } catch {
      setCashAccounts([]);
    }
    setShowPayModal(true);
  }, [editBill, form.payment_method, activeCompanyId, workCtx?.companyId]);

  const handlePayBill = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editBill || payForm.amount <= 0) return;
    if (!payForm.cash_account) {
      setError("Akun kas/bank sumber dana wajib dipilih");
      return;
    }
    const matchedMethod = findPaymentMethod(paymentMethods, payForm.payment_method.trim());
    if (!matchedMethod) {
      setError("Metode pembayaran wajib dipilih");
      return;
    }
    setPaySubmitting(true);
    setError(null);
    try {
      const userId = (pb.authStore.model?.id as string | undefined) || editBill.created_by || "";
      await applyBillPayment({
        bill: editBill,
        amount: payForm.amount,
        paymentDate: payForm.payment_date,
        paymentMethod: matchedMethod,
        cashAccountId: payForm.cash_account,
        notes: payForm.notes,
        createdBy: userId,
      });
      setShowPayModal(false);
      await reloadEditBill();
    } catch (err: unknown) {
      setError(getErrorMessage(err, "Gagal menyimpan pembayaran hutang"));
    } finally {
      setPaySubmitting(false);
    }
  };

  const handleActionSave = async () => {
    const target = await persistDocument();
    if (!target) return;
    if (isEdit || isPoEdit) {
      try {
        await reloadShippingFromPersist(target);
      } catch {
        /* abaikan */
      }
      setDocViewLocked(true);
      if (isEdit) await reloadEditBill();
    } else {
      resetToNew();
    }
  };

  const handleActionPrint = async () => {
    const target = await persistDocument();
    if (!target) return;
    const payload = await buildPurchasePostSavePayload(target, selectedStore ?? null);
    openBizDocumentPrint(payload.printData);
    if (!isEdit && !isPoEdit) {
      resetToNew();
    } else {
      try {
        await reloadShippingFromPersist(target);
      } catch {
        /* abaikan */
      }
      setDocViewLocked(true);
      if (isEdit) await reloadEditBill();
    }
  };

  const fieldInput =
    "w-full rounded-md border border-slate-200 px-2.5 py-1.5 text-sm text-slate-800 focus:border-indigo-400 focus:outline-none focus:ring-1 focus:ring-indigo-100";
  const fieldLabel = "mb-0.5 block text-xs font-medium text-slate-600";

  const productOptionLabel = (p: Product) =>
    showProductStock
      ? t("purchase.create.productStockTitle", {
          name: p.name,
          stock: fmtNum(getWarehouseStockQty(stockMap, p.id)),
        })
      : p.name;

  return (
    <div className="min-h-screen">
      <DocOpenChoiceModal
        open={!!docChoice}
        docNo={docChoice?.docNo ?? ""}
        docKind={docChoice?.mode === "bill" ? "tagihan pembelian" : "purchase order"}
        canRetur={docChoice?.canRetur}
        loading={docChoiceLoading}
        onClose={() => setDocChoice(null)}
        onEdit={() => docChoice && openDocForEdit(docChoice)}
        onRetur={
          docChoice?.canRetur
            ? () => {
                const poId = docChoice.mode === "bill" ? docChoice.poId : docChoice.poId;
                void startReturFromPo(poId);
              }
            : undefined
        }
      />
      {isPoEdit && poWorkflow ? (
        <div className="border-b border-amber-100 bg-amber-50/30 px-4 py-3 sm:px-6">
          <PurchaseQcExceptionPanel
            po={poWorkflow}
            onFinalized={async () => {
              if (!editPoId) return;
              setTimelinePo(await fetchPurchaseOrder(editPoId));
            }}
          />
        </div>
      ) : null}
      <div className="mb-3 flex flex-wrap items-start justify-between gap-3">
        <div className="flex min-w-0 flex-1 flex-wrap items-start gap-3">
          <Link
            href="/bisnis/pembelian"
            className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:border-slate-400 hover:bg-slate-50"
          >
            <ArrowLeft className="h-4 w-4" />
            {t("purchase.create.actionBack")}
          </Link>
          <div className="min-w-0 pt-0.5">
            <h1 className="text-lg font-bold text-slate-900">
              {isEdit
                ? t("purchase.create.titleEdit")
                : isPoEdit
                  ? t("purchase.create.titleEditPo")
                  : isBillCreate
                    ? t("purchase.create.titleNewBill")
                    : t("purchase.create.titleNewPo")}
            </h1>
            {!isEdit && !isPoEdit && !isBillCreate ? (
              <label className="mt-1 inline-flex items-center gap-1.5 text-[11px] text-slate-600">
                <input
                  type="checkbox"
                  checked={form.send_to_warehouse}
                  onChange={(e) => setForm((f) => ({ ...f, send_to_warehouse: e.target.checked }))}
                  className="h-3.5 w-3.5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                />
                {t("purchase.create.viaWms")}
              </label>
            ) : !isEdit && !isPoEdit ? (
              <p className="mt-0.5 text-[11px] leading-snug text-amber-800">
                {isBillCreate ? t("purchase.create.hintBill") : t("purchase.create.hintPo")}
              </p>
            ) : null}
          </div>
        </div>
        <div className="shrink-0 text-right">
          <span className="text-xs text-slate-500">{t("purchase.create.total")}</span>
          <div className="text-lg font-bold tabular-nums text-slate-900">{fmt(grandTotal)}</div>
        </div>
      </div>

      {loadingEdit && (
        <div className="mb-4 flex items-center gap-2 text-sm text-slate-500">
          <Loader2 className="h-4 w-4 animate-spin text-indigo-600" />
          {t("purchase.create.loading")}
        </div>
      )}

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 whitespace-pre-line">
          {error}
        </div>
      )}

      <div className="rounded-lg border border-slate-200 bg-white shadow-sm">
        <div className={fieldsLocked ? "pointer-events-none select-none [&_input]:bg-slate-50/90 [&_select]:bg-slate-50/90 [&_textarea]:bg-slate-50/90" : ""}>
        <div
          className={
            showShippingPanel
              ? "lg:grid lg:grid-cols-[1fr_17rem] xl:grid-cols-[1fr_20rem] lg:items-start"
              : ""
          }
        >
          <div className="min-w-0">
        <div className="border-b border-slate-100 px-3 py-3 sm:px-4">
          <div
            className={`grid grid-cols-2 gap-x-3 gap-y-2 md:grid-cols-4 ${
              showShippingPanel ? "xl:grid-cols-4" : "xl:grid-cols-6"
            }`}
          >
            <div className="col-span-2 md:col-span-2 xl:col-span-2">
              <label className={fieldLabel}>{t("purchase.create.supplier")} <span className="text-red-500">*</span></label>
              <select data-nav value={form.supplier} onChange={(e) => selectSupplier(e.target.value)} onKeyDown={onEnterFocusNext}
                className={fieldInput}>
                <option value="">{t("purchase.create.selectSupplier")}</option>
                {suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              {form.supplier && (
                <p className="mt-0.5 text-[10px] text-slate-400">
                  {pickAddress(suppliers.find((s) => s.id === form.supplier)) || "—"}
                </p>
              )}
            </div>
            <div>
              <div className="mb-0.5 flex items-center justify-between gap-1">
                <label className={fieldLabel.replace("mb-0.5 ", "")}>{t("sales.create.email")}</label>
                <ShippingInfoToggle shipping={shipping} onChange={handleShippingChange} />
              </div>
              <input data-nav type="email" value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} onKeyDown={onEnterFocusNext}
                className={fieldInput} />
            </div>
            <div>
              <label className={fieldLabel}>{t("sales.create.transactionDate")}</label>
              <input data-nav type="date" value={form.transaction_date} onChange={(e) => setForm((f) => ({ ...f, transaction_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className={fieldInput} />
            </div>
            <div>
              <label className={fieldLabel} title={docNumberFormatHint(usesBillNo ? "BILL" : "PO")}>
                {t(usesBillNo ? "purchase.create.billNo" : "purchase.create.poNo")}
              </label>
              <input
                data-nav
                type="text"
                value={form.transaction_no}
                onChange={(e) => setForm((f) => ({ ...f, transaction_no: e.target.value }))}
                onBlur={() => void handleDocNoBlur()}
                onKeyDown={onEnterFocusNext}
                placeholder={t(usesBillNo ? "purchase.create.billNoPlaceholder" : "purchase.create.poNoPlaceholder")}
                className={`${fieldInput} font-mono bg-slate-50`}
              />
            </div>
            <div>
              <label className={fieldLabel}>{t("purchase.create.paymentTerm")}</label>
              <select data-nav value={form.payment_term} onKeyDown={onEnterFocusNext} onChange={(e) => {
                const termId = e.target.value;
                const term = paymentTerms.find((x) => x.id === termId);
                if (term) {
                  const dd = new Date(form.transaction_date || Date.now());
                  dd.setDate(dd.getDate() + term.days);
                  setForm((f) => ({ ...f, payment_term: termId, due_date: dd.toISOString().slice(0, 10) }));
                } else {
                  setForm((f) => ({ ...f, payment_term: "" }));
                }
              }}
                className={fieldInput}>
                <option value="">{t("sales.create.selectTerm")}</option>
                {paymentTerms.map((pt) => <option key={pt.id} value={pt.id}>{pt.name}</option>)}
              </select>
            </div>
            <div>
              <label className={fieldLabel}>{t("purchase.create.dueDateLabel")}</label>
              <input data-nav type="date" value={form.due_date} onChange={(e) => setForm((f) => ({ ...f, due_date: e.target.value }))} onKeyDown={onEnterFocusNext}
                className={fieldInput} />
            </div>
            <div>
              <label className={fieldLabel}>{t("purchase.create.paymentMethod")}</label>
              <select data-nav value={form.payment_method} onChange={(e) => setForm((f) => ({ ...f, payment_method: e.target.value }))} onKeyDown={onEnterFocusNext}
                className={fieldInput}>
                <option value="">{paymentMethods.length === 0 ? t("purchase.create.noPaymentMethod") : t("purchase.create.selectMethod")}</option>
                {paymentMethods.map((m) => <option key={m.id} value={m.code || m.name}>{m.name}</option>)}
              </select>
            </div>
            <div className="col-span-2 md:col-span-2 xl:col-span-2">
              <label className={fieldLabel}>
                Entitas <span className="text-red-500">*</span>
              </label>
              {entityOptions.length === 0 ? (
                <p className="text-xs text-amber-600">
                  Belum ada entitas — buat di{" "}
                  <Link href="/pengaturan/perusahaan" className="font-medium underline">
                    Pengaturan → Perusahaan
                  </Link>
                </p>
              ) : entityOptions.length === 1 ? (
                <p className={`${fieldInput} bg-slate-50`}>{entityOptions[0].label}</p>
              ) : (
                <select
                  data-nav
                  value={activeCompanyId}
                  disabled={isEdit || isPoEdit}
                  onChange={(e) => void handleCompanyChange(e.target.value)}
                  onKeyDown={onEnterFocusNext}
                  className={`${fieldInput} disabled:bg-slate-50`}
                >
                  <option value="">Pilih entitas</option>
                  {entityOptions.map((c) => (
                    <option key={c.id} value={c.id}>{c.label}</option>
                  ))}
                </select>
              )}
              {receivingWarehouse ? (
                <p className="mt-0.5 text-[10px] text-slate-400">
                  Gudang: {receivingWarehouse.code} — {receivingWarehouse.name}
                  {form.warehouse ? (
                    <>
                      {" · "}
                      <Link href={`/gudang/stok?warehouse=${encodeURIComponent(form.warehouse)}`} className="text-indigo-600 hover:underline">
                        {stockLoading ? t("purchase.create.stockLoading") : t("purchase.create.viewWarehouseStock")}
                      </Link>
                    </>
                  ) : null}
                </p>
              ) : activeCompanyId ? (
                <p className="mt-0.5 text-[10px] text-amber-600">
                  Belum ada gudang entitas —{" "}
                  <Link href="/pengaturan/perusahaan" className="font-medium underline">setup perusahaan</Link>
                </p>
              ) : null}
            </div>
          </div>
          <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px]">
            <label className="flex cursor-pointer items-center gap-1.5 text-slate-600">
              <input
                type="checkbox"
                checked={form.include_tax}
                onChange={(e) => {
                  const checked = e.target.checked;
                  setForm((f) => {
                    if (!checked) return { ...f, include_tax: false };
                    if (f.tax_percent > 0) return { ...f, include_tax: true };
                    const def = taxRates.find((tr) => tr.is_default) ?? taxRates[0];
                    return def ? { ...f, include_tax: true, tax_percent: def.rate } : { ...f, include_tax: true };
                  });
                }}
                className="h-3.5 w-3.5 rounded border-slate-300 text-indigo-600"
              />
              {t("purchase.create.priceIncludesTax")}
            </label>
          </div>

          {showShippingPanel && !lgUp ? (
            <div className="mt-3 border-t border-sky-100 pt-3">
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-sky-800">
                {t("sales.shipping.panelTitle")}
              </p>
              <ShippingInfoSection
                shipping={shipping}
                onChange={handleShippingChange}
                showToggle={false}
                layout="sidebar"
                readOnly={fieldsLocked}
                includeAwb={false}
              />
            </div>
          ) : null}
        </div>

        <div>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-left">
                <th className="min-w-[12rem] px-3 py-3 text-xs font-semibold text-slate-600">{t("sales.create.product")}</th>
                <th className="w-28 px-2 py-3 text-center text-xs font-semibold text-slate-600">{t("purchase.create.qtyBuy")}</th>
                <th className="w-20 px-2 py-3 text-center text-xs font-semibold text-slate-600">{t("sales.create.unit")}</th>
                <th className="w-36 px-2 py-3 text-right text-xs font-semibold text-slate-600">{t("purchase.create.unitCost")}</th>
                <th className="w-32 px-2 py-3 text-center text-xs font-semibold text-slate-600">{t("sales.create.discount")}</th>
                <th className="w-32 px-2 py-3 text-right text-xs font-semibold text-slate-600">{t("sales.create.amount")}</th>
                <th className="w-10 px-1 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {lines.map((line, idx) => (
                <tr key={idx} className="group align-top">
                  <td className="min-w-0 px-3 py-2">
                    <select
                      data-line={idx}
                      data-field="product"
                      value={line.product}
                      onChange={(e) => updateLine(idx, "product", e.target.value)}
                      onKeyDown={(e) => onLineFieldEnter(e, idx)}
                      title={
                        line.product && showProductStock
                          ? (() => {
                              const p = products.find((x) => x.id === line.product);
                              if (!p) return undefined;
                              return t("purchase.create.productStockTitle", {
                                name: p.name,
                                stock: fmtNum(getWarehouseStockQty(stockMap, p.id)),
                              });
                            })()
                          : products.find((x) => x.id === line.product)?.name
                      }
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-sm text-slate-700 focus:border-indigo-400 focus:outline-none"
                    >
                      <option value="">{t("sales.create.selectProduct")}</option>
                      {products.map((p) => (
                        <option key={p.id} value={p.id}>{productOptionLabel(p)}</option>
                      ))}
                    </select>
                  </td>
                  <td className="w-28 px-2 py-2">
                    <NumSpinnerInput
                      className="w-full max-w-[6.5rem]"
                      data-line={idx}
                      data-field="qty"
                      value={line.qty}
                      min={1}
                      step={1}
                      onChange={(v) => updateLine(idx, "qty", v)}
                      onEnterNext={() => onLineSpinnerEnter(idx, "qty")}
                      inputClassName="w-full min-w-0 text-center text-sm"
                    />
                  </td>
                  <td className="w-20 px-2 py-2">
                    <input
                      type="text"
                      data-line={idx}
                      data-field="unit"
                      value={line.unit}
                      onChange={(e) => updateLine(idx, "unit", e.target.value)}
                      onKeyDown={(e) => onLineFieldEnter(e, idx)}
                      className="w-full min-w-0 rounded border border-slate-200 px-1.5 py-1.5 text-center text-sm text-slate-700 focus:border-indigo-400 focus:outline-none"
                    />
                  </td>
                  <td className="w-36 px-2 py-2">
                    <input
                      type="text"
                      inputMode="numeric"
                      data-line={idx}
                      data-field="unit_price"
                      value={line.unit_cost ? fmtNum(line.unit_cost) : ""}
                      onChange={(e) => updateLine(idx, "unit_cost", Math.max(0, parseNum(e.target.value)))}
                      onKeyDown={(e) => onLineFieldEnter(e, idx)}
                      className="w-full min-w-0 rounded border border-slate-200 px-2 py-1.5 text-right text-sm"
                    />
                  </td>
                  <td className="w-32 px-2 py-2">
                    <NumSpinnerInput
                      data-line={idx}
                      data-field="discount"
                      value={line.discount_percent}
                      min={0}
                      max={100}
                      suffix="%"
                      onChange={(v) => updateLine(idx, "discount_percent", v)}
                      onEnterNext={() => onLineSpinnerEnter(idx, "discount")}
                      inputClassName="w-full min-w-0 text-center text-sm"
                    />
                  </td>
                  <td className="w-32 px-2 py-2 text-right text-sm font-medium whitespace-nowrap">{fmt(calcLineTotal(line))}</td>
                  <td className="px-2 py-2">
                    <button type="button" onClick={() => removeLine(idx)} className="rounded p-1 text-slate-300 opacity-0 group-hover:opacity-100 hover:text-red-500">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="border-t border-slate-100 px-4 py-3">
          <button
            type="button"
            data-nav-add-line
            onClick={() => {
              const nextIdx = lines.length;
              addLine();
              setTimeout(() => {
                document.querySelector<HTMLElement>(`[data-line="${nextIdx}"][data-field="product"]`)?.focus();
              }, 50);
            }}
            className="inline-flex items-center gap-1 text-sm font-medium text-indigo-600 hover:text-indigo-700"
          >
            <Plus className="h-4 w-4" /> {t("sales.create.addLine")}
          </button>
        </div>
          </div>

          {showShippingPanel && lgUp ? (
            <aside className="border-l border-sky-100 bg-sky-50/30 px-3 py-3 sm:pr-4 lg:sticky lg:top-3 lg:max-h-[calc(100vh-5rem)] lg:overflow-y-auto xl:px-4">
              <p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-sky-800">
                {t("sales.shipping.panelTitle")}
              </p>
              <ShippingInfoSection
                shipping={shipping}
                onChange={handleShippingChange}
                showToggle={false}
                layout="sidebar"
                readOnly={fieldsLocked}
              />
            </aside>
          ) : null}
        </div>

        <div className="grid grid-cols-1 gap-0 border-t border-slate-200 lg:grid-cols-2">
          <div className="border-b border-slate-200 p-5 lg:border-b-0 lg:border-r">
            <div className="space-y-5">
              <div>
                <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                  {t("purchase.create.internalProcessNotes")}
                </p>
                <p className="mb-1.5 text-[10px] text-slate-400">{t("purchase.create.internalProcessNotesHint")}</p>
                <PurchaseProcessTimeline
                  purchaseOrder={timelinePo}
                  emptyLabel={t("purchase.create.processTimelineEmpty")}
                />
              </div>
              <div className="border-t border-slate-100 pt-4">
                <label className="mb-0.5 block text-sm font-medium text-slate-700">{t("sales.create.memo")}</label>
                <p className="mb-2 text-[11px] text-slate-500">{t("purchase.create.memoHint")}</p>
                <textarea
                  data-nav
                  rows={2}
                  value={form.memo}
                  onChange={(e) => setForm((f) => ({ ...f, memo: e.target.value }))}
                  onKeyDown={onEnterFocusNext}
                  placeholder={t("purchase.create.memoPlaceholder")}
                  className="w-full resize-y border-0 border-b border-slate-200 bg-transparent px-0 py-1.5 text-sm leading-relaxed text-slate-800 placeholder:text-slate-400 focus:border-indigo-400 focus:outline-none focus:ring-0"
                />
              </div>
            </div>
          </div>
          <div className="p-6">
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-600">{t("sales.create.subtotal")}</span>
                <span className="font-medium text-slate-900">{fmt(subtotal)}</span>
              </div>
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-slate-600">{t("sales.create.tax")}</span>
                  <select
                    data-nav
                    value={form.tax_percent}
                    onChange={(e) => {
                      const rate = Number(e.target.value);
                      setForm((f) => ({
                        ...f,
                        tax_percent: rate,
                        include_tax: rate === 0 ? false : f.include_tax,
                      }));
                    }}
                    onKeyDown={onEnterFocusNext}
                    className="rounded border border-slate-200 px-2 py-0.5 text-xs text-slate-600"
                  >
                    <option value={0}>{t("sales.create.noTax")}</option>
                    {taxRates.map((tr) => <option key={tr.id} value={tr.rate}>{tr.name}</option>)}
                  </select>
                  {form.include_tax && (
                    <span className="text-[11px] font-medium text-indigo-600">{t("sales.create.taxIncluded")}</span>
                  )}
                </div>
                <span className="text-slate-500">{fmt(totalTax)}</span>
              </div>
              <div className="flex items-center justify-between gap-2">
                <span className="text-slate-600">{t("sales.create.stampDuty")}</span>
                <input
                  data-nav
                  type="text"
                  inputMode="numeric"
                  value={form.materai_amount ? fmtNum(form.materai_amount) : ""}
                  onChange={(e) => setForm((f) => ({ ...f, materai_amount: Math.max(0, parseNum(e.target.value)) }))}
                  onKeyDown={onEnterFocusNext}
                  placeholder="0"
                  className="w-32 rounded border border-slate-200 px-2 py-0.5 text-right text-xs text-slate-700"
                />
              </div>
              {shippingCost > 0 && (
                <div className="flex justify-between">
                  <span className="text-slate-600">{t("sales.create.shipping")}</span>
                  <span className="text-slate-500">{fmt(shippingCost)}</span>
                </div>
              )}
              <div className="flex justify-between border-t border-slate-200 pt-3">
                <span className="text-base font-bold text-slate-900">{t("sales.create.grandTotal")}</span>
                <span className="text-base font-bold text-slate-900">{fmt(grandTotal)}</span>
              </div>
              {isEdit && editBill ? (
                <div className="flex justify-between border-t border-slate-200 pt-3">
                  <span className="font-semibold text-slate-700">{t("purchase.create.remaining")}</span>
                  <span className="text-lg font-bold text-slate-900">{fmt(billRemaining)}</span>
                </div>
              ) : null}
            </div>
          </div>
        </div>
        </div>

        {isPoEdit && editPoId && !linkedBill && poWorkflow?.status !== "cancelled" ? (
          <div className="border-t border-sky-100 bg-sky-50/60 px-4 py-3 sm:px-6">
            <p className="text-sm text-sky-950">
              {poWorkflow?.send_to_warehouse_at
                ? t("purchase.create.poWmsBillHint")
                : t("purchase.create.poNoWmsHint")}
            </p>
            {billBlockReason && !canBillFromPo ? (
              <p className="mt-1 text-xs text-amber-800">{billBlockReason}</p>
            ) : null}
          </div>
        ) : null}

        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-4 py-4 sm:px-6">
          <div className="flex flex-wrap items-center gap-2">
            {canPayBill ? (
              <button
                type="button"
                onClick={() => void openPayModal()}
                disabled={paySubmitting}
                className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-700 disabled:opacity-50"
              >
                <CreditCard className="h-4 w-4" />
                {t("purchase.create.actionPayBill")}
              </button>
            ) : null}
            {isPoEdit && editPoId ? (
              <>
                {linkedBill ? (
                  <Link
                    href={`/bisnis/pembelian/buat?edit=${linkedBill.id}`}
                    className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700"
                  >
                    <FileText className="h-4 w-4" />
                    {t("purchase.create.actionViewBill")}
                  </Link>
                ) : canBillFromPo ? (
                  <button
                    type="button"
                    onClick={() => void handleCreateBillFromPo()}
                    disabled={creatingBill || submitting || sendingWarehouse || cancellingPo}
                    className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-700 disabled:opacity-50"
                  >
                    {creatingBill ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <FileText className="h-4 w-4" />
                    )}
                    {t("purchase.create.actionCreateBill")}
                  </button>
                ) : !linkedBill && billBlockReason ? (
                  <button
                    type="button"
                    disabled
                    title={billBlockReason}
                    className="inline-flex cursor-not-allowed items-center gap-2 rounded-lg bg-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-500"
                  >
                    <FileText className="h-4 w-4" />
                    {t("purchase.create.actionCreateBill")}
                  </button>
                ) : null}
                {canSendWhFromPo ? (
                  <button
                    type="button"
                    onClick={() => void handleSendPoToWarehouse()}
                    disabled={sendingWarehouse || submitting || creatingBill || cancellingPo}
                    className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-violet-700 disabled:opacity-50"
                  >
                    {sendingWarehouse ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <FileText className="h-4 w-4" />
                    )}
                    {t("purchase.create.actionSendWarehouse")}
                  </button>
                ) : null}
                {canCancelOpenPo ? (
                  <button
                    type="button"
                    onClick={() => void handleCancelOpenPo()}
                    disabled={cancellingPo || submitting || creatingBill || sendingWarehouse}
                    className="inline-flex items-center gap-2 rounded-lg border border-red-300 bg-red-50 px-4 py-2.5 text-sm font-medium text-red-800 transition hover:bg-red-100 disabled:opacity-50"
                  >
                    {cancellingPo ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Ban className="h-4 w-4" />
                    )}
                    {t("purchase.create.actionCancelPo")}
                  </button>
                ) : null}
              </>
            ) : null}
            {(isEdit || isPoEdit) && editCanRetur && editPoId ? (
              <button
                type="button"
                onClick={() => void handleEditRetur()}
                disabled={submitting || docChoiceLoading}
                className="inline-flex items-center gap-2 rounded-lg border border-amber-300 bg-amber-50 px-4 py-2.5 text-sm font-medium text-amber-900 transition hover:bg-amber-100 disabled:opacity-50"
              >
                <RotateCcw className="h-4 w-4" />
                {t("sales.create.actionRetur")}
              </button>
            ) : null}
          </div>
          <div className="flex flex-wrap items-center justify-end gap-2 sm:gap-3">
            {fieldsLocked ? (
              <>
                <button
                  type="button"
                  onClick={() => void handleViewPrint()}
                  className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 sm:px-5"
                >
                  <Printer className="h-4 w-4" />
                  {t("purchase.create.actionPrint")}
                </button>
                <button
                  type="button"
                  onClick={() => setDocViewLocked(false)}
                  className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-slate-800 sm:px-5"
                >
                  <Pencil className="h-4 w-4" />
                  {t("purchase.create.actionEdit")}
                </button>
              </>
            ) : (
              <>
                <button
                  type="button"
                  onClick={handleActionCancel}
                  disabled={submitting}
                  className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:opacity-50 sm:px-5"
                >
                  {t("purchase.create.actionCancel")}
                </button>
                <button
                  type="button"
                  onClick={() => void handleActionPrint()}
                  disabled={submitting}
                  className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:opacity-50 sm:px-5"
                >
                  {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Printer className="h-4 w-4" />}
                  {t("purchase.create.actionPrint")}
                </button>
                <button
                  type="button"
                  onClick={() => void handleActionSave()}
                  disabled={submitting}
                  className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-slate-800 disabled:opacity-50 sm:px-5"
                >
                  {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
                  {t("purchase.create.actionSave")}
                </button>
              </>
            )}
          </div>
        </div>
      </div>

      {showPayModal && editBill ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-md rounded-2xl bg-white shadow-xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
              <h2 className="text-lg font-semibold text-slate-900">{t("purchase.create.payBillTitle")}</h2>
              <button type="button" onClick={() => setShowPayModal(false)} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100">
                <X className="h-5 w-5" />
              </button>
            </div>
            <form onSubmit={(e) => void handlePayBill(e)} className="space-y-4 px-6 py-5">
              <div className="rounded-lg bg-slate-50 px-4 py-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-slate-500">{t("sales.create.grandTotal")}</span>
                  <span className="font-semibold text-slate-900">{fmt(editBill.total)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">{t("purchase.create.paidAmount")}</span>
                  <span className="text-emerald-600">{fmt(editBill.paid_amount)}</span>
                </div>
                <div className="mt-2 flex justify-between border-t border-slate-200 pt-2 font-bold">
                  <span className="text-slate-700">{t("purchase.create.remaining")}</span>
                  <span className="text-red-600">{fmt(editBill.remaining)}</span>
                </div>
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">{t("purchase.create.payAmount")}</label>
                <input
                  type="text"
                  inputMode="numeric"
                  required
                  value={payForm.amount ? fmtNum(payForm.amount) : ""}
                  onChange={(e) => setPayForm((f) => ({ ...f, amount: parseNum(e.target.value) }))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">{t("purchase.create.paymentMethod")}</label>
                <select
                  required
                  value={payForm.payment_method}
                  onChange={(e) => setPayForm((f) => ({ ...f, payment_method: e.target.value }))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                >
                  <option value="">{t("purchase.create.selectMethod")}</option>
                  {paymentMethods.map((m) => (
                    <option key={m.id} value={m.code || m.name}>{m.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">Akun kas/bank</label>
                <select
                  required
                  value={payForm.cash_account}
                  onChange={(e) => setPayForm((f) => ({ ...f, cash_account: e.target.value }))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                >
                  <option value="">Pilih akun</option>
                  {cashAccounts.map((a) => (
                    <option key={a.id} value={a.id}>{a.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="mb-1 block text-sm font-medium text-slate-700">{t("sales.create.transactionDate")}</label>
                <input
                  type="date"
                  required
                  value={payForm.payment_date}
                  onChange={(e) => setPayForm((f) => ({ ...f, payment_date: e.target.value }))}
                  className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
                />
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <button type="button" onClick={() => setShowPayModal(false)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
                  {t("purchase.create.actionCancel")}
                </button>
                <button type="submit" disabled={paySubmitting} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50">
                  {paySubmitting && <Loader2 className="h-4 w-4 animate-spin" />}
                  {t("purchase.create.actionPayBill")}
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  );
}
